<?php

use Illuminate\Database\Seeder;

class CityTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
   	public function run()
    {
        DB::table('city')->delete();

        $city = array(
                    array('name' => 'Abhipur', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 28,),
                    array('name' => 'Abohar', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 28,),
                    array('name' => 'Adilabad', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 32,),
                    array('name' => 'Agartala', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 33,),
                    array('name' => 'Agra', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Ahmedabad', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 12,),
                    array('name' => 'Ahmedgarh', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 28,),
                    array('name' => 'Ahmednagar', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 21,),
                    array('name' => 'Aizawl', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 24,),
                    array('name' => 'Ajmer', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 29,),
                    array('name' => 'Akola', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 21,),
                    array('name' => 'Aligarh', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Allahabad', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Almora', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 35,),
                    array('name' => 'Alwar', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 29,),
                    array('name' => 'Ambala', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 13,),
                    array('name' => 'Ambedkar Nagar', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Amethi', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Amloh', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 28,),
                    array('name' => 'Amravati', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 21,),
                    array('name' => 'Amritsar', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 28,),
                    array('name' => 'Amroha', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Anand', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 12,),
                    array('name' => 'Anandpur Sahib', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 28,),
                    array('name' => 'Anantapur', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 2,),
                    array('name' => 'Anantnag', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 15,),
                    array('name' => 'Andaman Islands', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 1,),
                    array('name' => 'Andhra Pradesh - Other', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 2,),
                    array('name' => 'Arrah', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 5,),
                    array('name' => 'Arunachal Pradesh - Other', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 3,),
                    array('name' => 'Asansol', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 36,),
                    array('name' => 'Assam - Other', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 4,),
                    array('name' => 'Auraiya', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Aurangabad', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 21,),
                    array('name' => 'Ayodhya', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Azamgarh', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Bageshwar', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 35,),
                    array('name' => 'Baghmara', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 23,),
                    array('name' => 'Baghpat', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Bahadurgarh', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 13,),
                    array('name' => 'Baheri', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 5,),
                    array('name' => 'Bahraich', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Ballia', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Balrampur', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Bambhori', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 21,),
                    array('name' => 'Banda', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Bangalore / Bengalooru', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 17,),
                    array('name' => 'Banka', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 5,),
                    array('name' => 'Banur', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 28,),
                    array('name' => 'Barabanki', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Barauni', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 5,),
                    array('name' => 'Barddhaman', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 36,),
                    array('name' => 'Bareilly', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Barhi', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 16,),
                    array('name' => 'Bari Brahmana', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 15,),
                    array('name' => 'Barnala', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 28,),
                    array('name' => 'Bassi', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 28,),
                    array('name' => 'Basti', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Batala', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 28,),
                    array('name' => 'Bathinda', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 28,),
                    array('name' => 'Beed', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 21,),
                    array('name' => 'Begusarai', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 5,),
                    array('name' => 'Belgaum', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 17,),
                    array('name' => 'Benipatti', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 5,),
                    array('name' => 'Betul', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 20,),
                    array('name' => 'Bhadohi', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Bhagalpur', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 5,),
                    array('name' => 'Bhandara', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 21,),
                    array('name' => 'Bharatpur', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 29,),
                    array('name' => 'Bhatpara', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Bhavnagar', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 12,),
                    array('name' => 'Bhilai', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 7,),
                    array('name' => 'Bhilwara', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 29,),
                    array('name' => 'Bhimtal', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 35,),
                    array('name' => 'Bhiwadi', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 29,),
                    array('name' => 'Bhiwani', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 13,),
                    array('name' => 'Bhopal', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 20,),
                    array('name' => 'Bhubaneswar', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 26,),
                    array('name' => 'Bihar - Other', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 5,),
                    array('name' => 'Biharsharif', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 5,),
                    array('name' => 'Bijapur', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 17,),
                    array('name' => 'Bijnor', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Bikaner', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 29,),
                    array('name' => 'Bilaspur', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 14,),
                    array('name' => 'Bilaspur', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 7,),
                    array('name' => 'Birbhum', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 36,),
                    array('name' => 'Bishrampur', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 7,),
                    array('name' => 'Bodh Gaya', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 5,),
                    array('name' => 'Bokaro', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 16,),
                    array('name' => 'Brahmapur (Berhampur)', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 26,),
                    array('name' => 'Budaun', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Bulandshahr', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Burdwan', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 36,),
                    array('name' => 'Buxar', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 5,),
                    array('name' => 'Calicut', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 18,),
                    array('name' => 'Central Delhi', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 10,),
                    array('name' => 'Chaibasa', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 16,),
                    array('name' => 'Chamba', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 14,),
                    array('name' => 'Champawat', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 35,),
                    array('name' => 'Chandauli', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Chandigarh', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 28,),
                    array('name' => 'Chandigarh', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 6,),
                    array('name' => 'Changa', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 12,),
                    array('name' => 'Chapra', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 5,),
                    array('name' => 'Chenari', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 5,),
                    array('name' => 'Chennai', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 31,),
                    array('name' => 'Chhattisgarh - Other', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 7,),
                    array('name' => 'Chikhli', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 12,),
                    array('name' => 'Chitrakoot', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 35,),
                    array('name' => 'Cochin/Kochi', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 18,),
                    array('name' => 'Coimbatore', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 31,),
                    array('name' => 'Coorg', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 17,),
                    array('name' => 'Cuttack', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 26,),
                    array('name' => 'Dabwali', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 13,),
                    array('name' => 'Dadra and Nagar Haveli - Other', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 8,),
                    array('name' => 'Dahod', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 12,),
                    array('name' => 'Dakpathar', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 35,),
                    array('name' => 'Dalsingsarai', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 5,),
                    array('name' => 'Daltonganj', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 16,),
                    array('name' => 'Daman', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 9,),
                    array('name' => 'Daman and Diu - Other', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 9,),
                    array('name' => 'Darbhanga', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 5,),
                    array('name' => 'Daudnagar', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 5,),
                    array('name' => 'Davanagere', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 17,),
                    array('name' => 'Dehradun', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 35,),
                    array('name' => 'Dehri', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 5,),
                    array('name' => 'Deogarh', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Deogarh (Jharkhand)', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 16,),
                    array('name' => 'Deogarh (Madhya Pradesh)', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 20,),
                    array('name' => 'Deogarh (Orissa)', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 26,),
                    array('name' => 'Deogarh (Rajasthan)', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 29,),
                    array('name' => 'Deoria', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Dewas', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 20,),
                    array('name' => 'Dhalai District', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 33,),
                    array('name' => 'Dhanbad', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 16,),
                    array('name' => 'Dharamsala', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 14,),
                    array('name' => 'Dharupur', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Dharwad', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 17,),
                    array('name' => 'Dhudike Moga', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 28,),
                    array('name' => 'Dhule', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 21,),
                    array('name' => 'Dhuri', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 28,),
                    array('name' => 'Dimapur', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 25,),
                    array('name' => 'Dinanagar', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 28,),
                    array('name' => 'Dispur', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 4,),
                    array('name' => 'Dumka', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 16,),
                    array('name' => 'Durg', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 7,),
                    array('name' => 'Durgapur', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 36,),
                    array('name' => 'Dwarahat', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 35,),
                    array('name' => 'Dwarka', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 12,),
                    array('name' => 'East', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 30,),
                    array('name' => 'East Champaran', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 5,),
                    array('name' => 'East Delhi', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 10,),
                    array('name' => 'Electronic City', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 17,),
                    array('name' => 'Ernakulam', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 18,),
                    array('name' => 'Erode', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 31,),
                    array('name' => 'Etah', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Etawah', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Faizabad', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Faridabad', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 13,),
                    array('name' => 'Faridabad', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 10,),
                    array('name' => 'Faridkot', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 28,),
                    array('name' => 'Farrukhabad', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Fatehgarh Sahib', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 28,),
                    array('name' => 'Fatehpur', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Fatehpur (Punjab)', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 28,),
                    array('name' => 'Fazilka', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 28,),
                    array('name' => 'Firozabad', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Firozpur', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 28,),
                    array('name' => 'Gandhinagar', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 12,),
                    array('name' => 'Gangolihat', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 35,),
                    array('name' => 'Gangtok', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 30,),
                    array('name' => 'Garhmukteshwar', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Gautam Buddh Nagar', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 10,),
                    array('name' => 'Gaya', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 5,),
                    array('name' => 'Ghatshila', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 16,),
                    array('name' => 'Ghaziabad', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 10,),
                    array('name' => 'Ghaziabad', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Ghazipur', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Ghoghardiha', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 5,),
                    array('name' => 'Giridih', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 16,),
                    array('name' => 'Goa - Other', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 11,),
                    array('name' => 'Gobindgarh', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 28,),
                    array('name' => 'Gogri', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 5,),
                    array('name' => 'Gomoh', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 16,),
                    array('name' => 'Gonda', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Gondia', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 21,),
                    array('name' => 'Gorakhpur', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Greater Noida', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 10,),
                    array('name' => 'Gujarat - Other', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 12,),
                    array('name' => 'Gulbarga', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 17,),
                    array('name' => 'Guntur', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 2,),
                    array('name' => 'Gurdaspur', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 28,),
                    array('name' => 'Gurgaon', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 13,),
                    array('name' => 'Gurgaon', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 10,),
                    array('name' => 'Guwahati', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 4,),
                    array('name' => 'Gwalior', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 20,),
                    array('name' => 'Haldwani', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 35,),
                    array('name' => 'Hamirpur', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 14,),
                    array('name' => 'Hardoi', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Haridwar', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 35,),
                    array('name' => 'Haryana - Other', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 13,),
                    array('name' => 'Hathras', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Hazaribagh', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 16,),
                    array('name' => 'Himachal Pradesh - Other', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 14,),
                    array('name' => 'Himatnagar', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 12,),
                    array('name' => 'Himmat Nagar', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 2,),
                    array('name' => 'Hisar', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 13,),
                    array('name' => 'Hoshiarpur', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 28,),
                    array('name' => 'Howrah', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 36,),
                    array('name' => 'Hubli', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 17,),
                    array('name' => 'Hugli', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 36,),
                    array('name' => 'Hyderabad', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 2,),
                    array('name' => 'Hyderabad', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 32,),
                    array('name' => 'Ichalkaranji', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 21,),
                    array('name' => 'Imphal', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 22,),
                    array('name' => 'Indore', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 20,),
                    array('name' => 'Islampur', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 5,),
                    array('name' => 'Itanagar', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 3,),
                    array('name' => 'Itkhori', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 16,),
                    array('name' => 'Jabalpur', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 20,),
                    array('name' => 'Jagdishpur', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Jainagar', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 5,),
                    array('name' => 'Jaipur', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 29,),
                    array('name' => 'Jalalabad', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Jalandhar', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 28,),
                    array('name' => 'Jalaun', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Jalgaon', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 21,),
                    array('name' => 'Jammu', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 15,),
                    array('name' => 'Jammu & Kashmir - Other', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 15,),
                    array('name' => 'Jamnagar', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 12,),
                    array('name' => 'Jamshedpur', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 16,),
                    array('name' => 'Japla', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 16,),
                    array('name' => 'Jaspur', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 35,),
                    array('name' => 'Jaunpur', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Jehanabad', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 5,),
                    array('name' => 'Jhajjar', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 13,),
                    array('name' => 'Jhansi', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Jharkhand - Other', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 16,),
                    array('name' => 'Jhumri Tilaiya', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 16,),
                    array('name' => 'Jhunjhunu / Churu', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 29,),
                    array('name' => 'Jodhpur', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 29,),
                    array('name' => 'Junagadh', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 12,),
                    array('name' => 'Kadaura', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Kaimur', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 5,),
                    array('name' => 'Kalapet', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 27,),
                    array('name' => 'Kaler', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 5,),
                    array('name' => 'Kalol', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 12,),
                    array('name' => 'Kancheepuram', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 31,),
                    array('name' => 'Kangra', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 14,),
                    array('name' => 'Kankavli', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 21,),
                    array('name' => 'Kannauj', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Kannur', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 18,),
                    array('name' => 'Kanpur', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Kanpur Dehat', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Kanshiram Nagar', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Kanyakumari', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 31,),
                    array('name' => 'Kapurthala', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 28,),
                    array('name' => 'Karad', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 21,),
                    array('name' => 'Karikal', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 27,),
                    array('name' => 'Karimnagar', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 2,),
                    array('name' => 'Karimnagar', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 32,),
                    array('name' => 'Karjat', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 21,),
                    array('name' => 'Karnataka - Other', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 17,),
                    array('name' => 'Kasganj', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Kashipur', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 35,),
                    array('name' => 'Kashmir', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 15,),
                    array('name' => 'Kaul', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 13,),
                    array('name' => 'Kaushambi', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Kaziranga', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 4,),
                    array('name' => 'Kerala - Other', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 18,),
                    array('name' => 'Khajuraho', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 20,),
                    array('name' => 'Khammam', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 32,),
                    array('name' => 'Khanna', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 28,),
                    array('name' => 'Kharagpur', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 36,),
                    array('name' => 'Kharar', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 28,),
                    array('name' => 'Kheri', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Kichha', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 35,),
                    array('name' => 'Koch', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 5,),
                    array('name' => 'Koderma', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 16,),
                    array('name' => 'Kohima', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 25,),
                    array('name' => 'Kolhapur', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 21,),
                    array('name' => 'Kolkata / Calcutta', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 36,),
                    array('name' => 'Kollam', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 18,),
                    array('name' => 'Konark', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 26,),
                    array('name' => 'Korba', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 7,),
                    array('name' => 'Kota', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 29,),
                    array('name' => 'Kotdwara', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Kotkapura', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 28,),
                    array('name' => 'Kottayam', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 18,),
                    array('name' => 'Kozhikode', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 18,),
                    array('name' => 'Kukatpally', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 2,),
                    array('name' => 'Kumardhubi', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 16,),
                    array('name' => 'Kumbakonam', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 31,),
                    array('name' => 'Kurukshetra', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 13,),
                    array('name' => 'Kushinagar', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Laheriasarai', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 5,),
                    array('name' => 'Lakshdweep', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 19,),
                    array('name' => 'Lakshmipur', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 36,),
                    array('name' => 'Lalitpur', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Landran', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 28,),
                    array('name' => 'Latur', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 21,),
                    array('name' => 'Leh / Ladakh', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 15,),
                    array('name' => 'Lonavala', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 21,),
                    array('name' => 'Loni', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Lucknow', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Ludhiana', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 28,),
                    array('name' => 'Madhepura', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 5,),
                    array('name' => 'Madhubani', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 5,),
                    array('name' => 'Madhya Pradesh - Other', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 20,),
                    array('name' => 'Madurai', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 31,),
                    array('name' => 'Maharajganj', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Maharashtra - Other', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 21,),
                    array('name' => 'Mahbubnagar', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 32,),
                    array('name' => 'Mahe', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 27,),
                    array('name' => 'Mahoba', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Malerkotla', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 28,),
                    array('name' => 'Malout', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 28,),
                    array('name' => 'Manali', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 14,),
                    array('name' => 'Mandi', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 28,),
                    array('name' => 'Mangalore', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 17,),
                    array('name' => 'Manipal', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 17,),
                    array('name' => 'Manipur - Other', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 22,),
                    array('name' => 'Manjhaul', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 5,),
                    array('name' => 'Mansa', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 28,),
                    array('name' => 'Mapusa', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 11,),
                    array('name' => 'Margao', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 11,),
                    array('name' => 'Mathura', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Matunga', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 21,),
                    array('name' => 'Mau', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Mauranipur', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Medinipur', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 36,),
                    array('name' => 'Meerut', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Meghalaya - Other', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 23,),
                    array('name' => 'Mehsana', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 12,),
                    array('name' => 'Mewat', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 13,),
                    array('name' => 'Mhow', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 20,),
                    array('name' => 'Miraj', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 21,),
                    array('name' => 'Miryalaguda', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 32,),
                    array('name' => 'Mirzaganj', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 16,),
                    array('name' => 'Mirzapur', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Mizoram - Other', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 24,),
                    array('name' => 'Modi Nagar', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Moga', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 28,),
                    array('name' => 'Mohali', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 28,),
                    array('name' => 'Mohanpur', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 5,),
                    array('name' => 'Mohindargarh', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 13,),
                    array('name' => 'Mohiuddinnagar', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 5,),
                    array('name' => 'Moradabad', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Mukerian', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 28,),
                    array('name' => 'Mukteshwar', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 35,),
                    array('name' => 'Muktsar', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 28,),
                    array('name' => 'Mullana', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 13,),
                    array('name' => 'Mumbai', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 21,),
                    array('name' => 'Munger', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 5,),
                    array('name' => 'Munnar', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 18,),
                    array('name' => 'Munsiyari', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 35,),
                    array('name' => 'Murshidabad', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 36,),
                    array('name' => 'Mussoorie', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 35,),
                    array('name' => 'Muzaffarnagar', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Muzaffarpur', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 5,),
                    array('name' => 'Mysore', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 17,),
                    array('name' => 'Nabha', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 28,),
                    array('name' => 'Nadiad', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 12,),
                    array('name' => 'Nagaland - Other', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 25,),
                    array('name' => 'Nagaon', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 4,),
                    array('name' => 'Nagpur', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 21,),
                    array('name' => 'Nainital', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 35,),
                    array('name' => 'Nalanda', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 5,),
                    array('name' => 'Nalgonda', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 2,),
                    array('name' => 'Nalgonda', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 32,),
                    array('name' => 'Nanded', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 21,),
                    array('name' => 'Nangal', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 28,),
                    array('name' => 'Narhan', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 5,),
                    array('name' => 'Nashik', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 21,),
                    array('name' => 'Navi Mumbai', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 21,),
                    array('name' => 'Nawada', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 5,),
                    array('name' => 'Nawanshahr', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 28,),
                    array('name' => 'Nehra', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 5,),
                    array('name' => 'Nellore', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 2,),
                    array('name' => 'New Delhi', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 10,),
                    array('name' => 'Nicobar Islands', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 1,),
                    array('name' => 'Nizamabad', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 32,),
                    array('name' => 'Noida', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 10,),
                    array('name' => 'Noida', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'North', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 30,),
                    array('name' => 'North 24 Parganas(Urban areas)', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 36,),
                    array('name' => 'North Delhi', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 10,),
                    array('name' => 'North District', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 33,),
                    array('name' => 'North East Delhi', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 10,),
                    array('name' => 'North West Delhi', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 10,),
                    array('name' => 'Orissa / Odisha - Other', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 26,),
                    array('name' => 'Pakur', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 16,),
                    array('name' => 'Palakkad', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 18,),
                    array('name' => 'Palampur', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 14,),
                    array('name' => 'Palwal', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 10,),
                    array('name' => 'Panaji', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 11,),
                    array('name' => 'Panchkula', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 13,),
                    array('name' => 'Pandhiana', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 28,),
                    array('name' => 'Panipat', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 13,),
                    array('name' => 'Pant Nagar', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 35,),
                    array('name' => 'Panvel', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 21,),
                    array('name' => 'Parsa', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 5,),
                    array('name' => 'Pathankot', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 28,),
                    array('name' => 'Patiala', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 28,),
                    array('name' => 'Patna', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 5,),
                    array('name' => 'Patnacity', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 5,),
                    array('name' => 'Pauri', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 35,),
                    array('name' => 'Persathua', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 5,),
                    array('name' => 'Perundurai', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 31,),
                    array('name' => 'Phagwara', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 28,),
                    array('name' => 'Pilani', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 29,),
                    array('name' => 'Pilibhit', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Pithoragarh', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 35,),
                    array('name' => 'Pratapgarh', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 29,),
                    array('name' => 'Puducherry - Other', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 27,),
                    array('name' => 'Pune', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 21,),
                    array('name' => 'Punjab - Other', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 28,),
                    array('name' => 'Puri', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 26,),
                    array('name' => 'Pusa', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 5,),
                    array('name' => 'Rahika', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 5,),
                    array('name' => 'Raibareilly', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Raipur', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 7,),
                    array('name' => 'Raj Garh', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 20,),
                    array('name' => 'Rajasthan - Other', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 29,),
                    array('name' => 'Rajkot', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 12,),
                    array('name' => 'Rajnagar', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Rajpur', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Rajpur (West bengal)', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 36,),
                    array('name' => 'Rajpura', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 20,),
                    array('name' => 'Rajpura - Punjab', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 28,),
                    array('name' => 'Rajpura - Rajasthan', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 29,),
                    array('name' => 'Ramagundam', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 32,),
                    array('name' => 'Ramapuram', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 18,),
                    array('name' => 'Ramgarh', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 16,),
                    array('name' => 'Rampur', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Ranchi', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 16,),
                    array('name' => 'Ranga Reddy', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 2,),
                    array('name' => 'Ranikhet', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 35,),
                    array('name' => 'Rewa', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 20,),
                    array('name' => 'Rewari', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 10,),
                    array('name' => 'Rishikesh', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 35,),
                    array('name' => 'Rohtak', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 13,),
                    array('name' => 'Rohtas', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 5,),
                    array('name' => 'Roorkee', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 35,),
                    array('name' => 'Ropar', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 28,),
                    array('name' => 'Rosera', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 5,),
                    array('name' => 'Rourkela', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 26,),
                    array('name' => 'Rudrapur', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 35,),
                    array('name' => 'Rupnagar', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 28,),
                    array('name' => 'Sabour', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 5,),
                    array('name' => 'Sagar', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 20,),
                    array('name' => 'Saharanpur', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Sahibganj', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 16,),
                    array('name' => 'Salem', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 31,),
                    array('name' => 'Samastipur', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 5,),
                    array('name' => 'Sanghera', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 28,),
                    array('name' => 'Sangli', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 21,),
                    array('name' => 'Sangrur', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 28,),
                    array('name' => 'Sant Kabir Nagar', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Sarisabpahi', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 5,),
                    array('name' => 'Satara', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 21,),
                    array('name' => 'Secunderabad', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 2,),
                    array('name' => 'Sevagram', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 21,),
                    array('name' => 'Shahada', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 21,),
                    array('name' => 'Shahjahanpur', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Shamli', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Shekhpura', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 28,),
                    array('name' => 'Shikohabad', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Shillong', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 23,),
                    array('name' => 'Shimla', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 14,),
                    array('name' => 'Sikar', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 29,),
                    array('name' => 'Sikkim - Other', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 30,),
                    array('name' => 'Silchar', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 4,),
                    array('name' => 'Siliguri', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 36,),
                    array('name' => 'Sirhind', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 28,),
                    array('name' => 'Sirmaur', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 14,),
                    array('name' => 'Sirsa', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 13,),
                    array('name' => 'Sitamarhi', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 5,),
                    array('name' => 'Sitapur', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Siwan', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 5,),
                    array('name' => 'Sohsarai', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 5,),
                    array('name' => 'Solan', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 14,),
                    array('name' => 'Solapur', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 21,),
                    array('name' => 'Sonbhadra', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Sonepat', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 10,),
                    array('name' => 'South', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 30,),
                    array('name' => 'South 24 Parganas(Urban Areas)', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 36,),
                    array('name' => 'South Delhi', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 10,),
                    array('name' => 'South District', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 33,),
                    array('name' => 'South West Delhi', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 10,),
                    array('name' => 'Srinagar', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 15,),
                    array('name' => 'Sultanganj', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 5,),
                    array('name' => 'Sultanpur', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Sunam', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 28,),
                    array('name' => 'Sundernagar', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 14,),
                    array('name' => 'Surat', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 12,),
                    array('name' => 'Surathkal', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 17,),
                    array('name' => 'Surendranagar', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 12,),
                    array('name' => 'Suryapet', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 32,),
                    array('name' => 'Talwandi Sabo', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 28,),
                    array('name' => 'Talwari', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 35,),
                    array('name' => 'Tamil Nadu - Other', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 31,),
                    array('name' => 'Tangori', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 28,),
                    array('name' => 'Tarapur', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 21,),
                    array('name' => 'Tarn taran', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 28,),
                    array('name' => 'Tehri', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 35,),
                    array('name' => 'Tezpur', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 4,),
                    array('name' => 'Thane', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 21,),
                    array('name' => 'Thanjavur', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 31,),
                    array('name' => 'Thiruvallur', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 31,),
                    array('name' => 'Thiruvananthapuram', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 18,),
                    array('name' => 'Thrissur', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 18,),
                    array('name' => 'Tiruchengode', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 31,),
                    array('name' => 'Tirupati', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 2,),
                    array('name' => 'Tirupur', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 31,),
                    array('name' => 'Tonk', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 29,),
                    array('name' => 'Trichy / Tiruchirapalli', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 31,),
                    array('name' => 'Trimuhan', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 5,),
                    array('name' => 'Tripura - Other', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 33,),
                    array('name' => 'Tumkur', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 17,),
                    array('name' => 'Tuticorin', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 31,),
                    array('name' => 'Udaipur', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 29,),
                    array('name' => 'Udupi', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 17,),
                    array('name' => 'Ujjain', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 20,),
                    array('name' => 'Umrer', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 21,),
                    array('name' => 'Unnao', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Uttar Pradesh - Other', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Uttarakhand - Other', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 35,),
                    array('name' => 'Uttarkashi', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Vadodara', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 12,),
                    array('name' => 'Vaishali', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 5,),
                    array('name' => 'Varanasi', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 34,),
                    array('name' => 'Vasco Da Gama', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 11,),
                    array('name' => 'Vellore', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 31,),
                    array('name' => 'Vidyanagar', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 17,),
                    array('name' => 'Vijayawada', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 2,),
                    array('name' => 'Visakhapatnam/Vizag', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 2,),
                    array('name' => 'Warananagar', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 21,),
                    array('name' => 'Warangal', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 2,),
                    array('name' => 'Warangal', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 32,),
                    array('name' => 'Wardha', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 21,),
                    array('name' => 'West', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 30,),
                    array('name' => 'West Bengal - Other', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 36,),
                    array('name' => 'West Delhi', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 10,),
                    array('name' => 'West District', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 33,),
                    array('name' => 'Yaman', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 27,),
                    array('name' => 'Yamunanagar', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 13,),
                    array('name' => 'Yavatmal', 'cityStatus' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime, 'state_id' => 21,),


                   
        );

        DB::table('city')->insert( $city );
    }
}
