<?php

use Illuminate\Database\Seeder;

class CounselingBoardDetailsTableSeeder extends Seeder {

	/**
	 * Auto generated seed file
	 *
	 * @return void
	 */
	public function run()
	{
		\DB::table('counseling_board_details')->delete();
        
		\DB::table('counseling_board_details')->insert(array (
			0 => 
			array (
				'id' => 1,
				'title' => '',
				'description' => '',
				'image' => 'counseling-boards-cbse-1.jpg',
				'aboutBoard' => '',
				'admissionDesc' => '',
				'boardDesc' => '',
				'syllabusDesc' => '',
				'samplePaper' => '',
				'admitCardDetails' => '',
				'preprationTips' => '',
				'resultDesc' => '',
				'entranceExam' => '',
				'chooseRightCollege' => '',
				'counselingBoardId' => 1,
				'created_at' => '2020-04-23 12:26:07',
				'updated_at' => '2020-04-27 10:02:33',
				'employee_id' => 8233,
			),
			1 => 
			array (
				'id' => 2,
				'title' => '',
				'description' => '',
				'image' => 'counseling-boards-icse-2.jpg',
				'aboutBoard' => '',
				'admissionDesc' => '',
				'boardDesc' => '',
				'syllabusDesc' => '',
				'samplePaper' => '',
				'admitCardDetails' => '',
				'preprationTips' => '',
				'resultDesc' => '',
				'entranceExam' => '',
				'chooseRightCollege' => '',
				'counselingBoardId' => 2,
				'created_at' => '2020-04-23 12:26:08',
				'updated_at' => '2020-04-29 10:24:36',
				'employee_id' => 8233,
			),
			2 => 
			array (
				'id' => 3,
				'title' => '',
				'description' => '',
				'image' => 'counseling-boards-nios-3.jpeg',
				'aboutBoard' => '',
				'admissionDesc' => '',
				'boardDesc' => '',
				'syllabusDesc' => '',
				'samplePaper' => '',
				'admitCardDetails' => '',
				'preprationTips' => '',
				'resultDesc' => '',
				'entranceExam' => '',
				'chooseRightCollege' => '',
				'counselingBoardId' => 3,
				'created_at' => '2020-04-23 12:26:10',
				'updated_at' => '2020-04-29 10:24:01',
				'employee_id' => 8233,
			),
			3 => 
			array (
				'id' => 4,
				'title' => '',
				'description' => '',
				'image' => 'counseling-boards-jkbose-4.jpg',
				'aboutBoard' => '',
				'admissionDesc' => '',
				'boardDesc' => '',
				'syllabusDesc' => '',
				'samplePaper' => '',
				'admitCardDetails' => '',
				'preprationTips' => '',
				'resultDesc' => '',
				'entranceExam' => '',
				'chooseRightCollege' => '',
				'counselingBoardId' => 4,
				'created_at' => '2020-04-23 12:26:11',
				'updated_at' => '2020-04-29 10:23:24',
				'employee_id' => 8233,
			),
			4 => 
			array (
				'id' => 5,
				'title' => '',
				'description' => '',
				'image' => 'counseling-boards-rbse-5.jpg',
				'aboutBoard' => '',
				'admissionDesc' => '',
				'boardDesc' => '',
				'syllabusDesc' => '',
				'samplePaper' => '',
				'admitCardDetails' => '',
				'preprationTips' => '',
				'resultDesc' => '',
				'entranceExam' => '',
				'chooseRightCollege' => '',
				'counselingBoardId' => 5,
				'created_at' => '2020-04-23 12:26:16',
				'updated_at' => '2020-04-29 10:22:51',
				'employee_id' => 8233,
			),
			5 => 
			array (
				'id' => 6,
				'title' => '',
				'description' => '',
				'image' => 'counseling-boards-pseb-6.jpg',
				'aboutBoard' => '',
				'admissionDesc' => '',
				'boardDesc' => '',
				'syllabusDesc' => '',
				'samplePaper' => '',
				'admitCardDetails' => '',
				'preprationTips' => '',
				'resultDesc' => '',
				'entranceExam' => '',
				'chooseRightCollege' => '',
				'counselingBoardId' => 6,
				'created_at' => '2020-04-23 12:26:17',
				'updated_at' => '2020-04-29 10:22:05',
				'employee_id' => 8233,
			),
			6 => 
			array (
				'id' => 7,
				'title' => '',
				'description' => '',
				'image' => 'counseling-boards-bseb-7.jpg',
				'aboutBoard' => '',
				'admissionDesc' => '',
				'boardDesc' => '',
				'syllabusDesc' => '',
				'samplePaper' => '',
				'admitCardDetails' => '',
				'preprationTips' => '',
				'resultDesc' => '',
				'entranceExam' => '',
				'chooseRightCollege' => '',
				'counselingBoardId' => 7,
				'created_at' => '2020-04-23 12:26:19',
				'updated_at' => '2020-04-29 10:20:59',
				'employee_id' => 8233,
			),
			7 => 
			array (
				'id' => 8,
				'title' => '',
				'description' => '',
				'image' => 'counseling-boards-upmsp-8.jpg',
				'aboutBoard' => '',
				'admissionDesc' => '',
				'boardDesc' => '',
				'syllabusDesc' => '',
				'samplePaper' => '',
				'admitCardDetails' => '',
				'preprationTips' => '',
				'resultDesc' => '',
				'entranceExam' => '',
				'chooseRightCollege' => '',
				'counselingBoardId' => 8,
				'created_at' => '2020-04-23 12:26:25',
				'updated_at' => '2020-04-29 10:20:42',
				'employee_id' => 8233,
			),
			8 => 
			array (
				'id' => 9,
				'title' => '',
				'description' => '',
				'image' => 'counseling-boards-gseb-9.jpeg',
				'aboutBoard' => '',
				'admissionDesc' => '',
				'boardDesc' => '',
				'syllabusDesc' => '',
				'samplePaper' => '',
				'admitCardDetails' => '',
				'preprationTips' => '',
				'resultDesc' => '',
				'entranceExam' => '',
				'chooseRightCollege' => '',
				'counselingBoardId' => 9,
				'created_at' => '2020-04-23 12:26:27',
				'updated_at' => '2020-04-29 10:19:26',
				'employee_id' => 8233,
			),
			9 => 
			array (
				'id' => 10,
				'title' => '',
				'description' => '',
				'image' => 'counseling-boards-hpbose-10.jpg',
				'aboutBoard' => '',
				'admissionDesc' => '',
				'boardDesc' => '',
				'syllabusDesc' => '',
				'samplePaper' => '',
				'admitCardDetails' => '',
				'preprationTips' => '',
				'resultDesc' => '',
				'entranceExam' => '',
				'chooseRightCollege' => '',
				'counselingBoardId' => 10,
				'created_at' => '2020-04-23 12:26:28',
				'updated_at' => '2020-04-29 10:19:12',
				'employee_id' => 8233,
			),
			10 => 
			array (
				'id' => 11,
				'title' => '',
				'description' => '',
				'image' => 'counseling-boards-mpbse-11.jpg',
				'aboutBoard' => '',
				'admissionDesc' => '',
				'boardDesc' => '',
				'syllabusDesc' => '',
				'samplePaper' => '',
				'admitCardDetails' => '',
				'preprationTips' => '',
				'resultDesc' => '',
				'entranceExam' => '',
				'chooseRightCollege' => '',
				'counselingBoardId' => 11,
				'created_at' => '2020-04-23 12:26:29',
				'updated_at' => '2020-04-29 10:18:48',
				'employee_id' => 8233,
			),
			11 => 
			array (
				'id' => 12,
				'title' => '',
				'description' => '',
				'image' => 'counseling-boards-bieap-12.png',
				'aboutBoard' => '',
				'admissionDesc' => '',
				'boardDesc' => '',
				'syllabusDesc' => '',
				'samplePaper' => '',
				'admitCardDetails' => '',
				'preprationTips' => '',
				'resultDesc' => '',
				'entranceExam' => '',
				'chooseRightCollege' => '',
				'counselingBoardId' => 12,
				'created_at' => '2020-04-23 12:26:31',
				'updated_at' => '2020-04-29 10:18:32',
				'employee_id' => 8233,
			),
			12 => 
			array (
				'id' => 13,
				'title' => '',
				'description' => '',
				'image' => 'counseling-boards-wbchse-13.jpg',
				'aboutBoard' => '',
				'admissionDesc' => '',
				'boardDesc' => '',
				'syllabusDesc' => '',
				'samplePaper' => '',
				'admitCardDetails' => '',
				'preprationTips' => '',
				'resultDesc' => '',
				'entranceExam' => '',
				'chooseRightCollege' => '',
				'counselingBoardId' => 13,
				'created_at' => '2020-04-23 12:26:45',
				'updated_at' => '2020-04-29 10:17:56',
				'employee_id' => 8233,
			),
			13 => 
			array (
				'id' => 14,
				'title' => '',
				'description' => '',
				'image' => 'counseling-boards-wbbse-14.png',
				'aboutBoard' => '',
				'admissionDesc' => '',
				'boardDesc' => '',
				'syllabusDesc' => '',
				'samplePaper' => '',
				'admitCardDetails' => '',
				'preprationTips' => '',
				'resultDesc' => '',
				'entranceExam' => '',
				'chooseRightCollege' => '',
				'counselingBoardId' => 14,
				'created_at' => '2020-04-23 12:26:46',
				'updated_at' => '2020-04-29 10:17:32',
				'employee_id' => 8233,
			),
			14 => 
			array (
				'id' => 15,
				'title' => '',
				'description' => '',
				'image' => 'counseling-boards-cgbse-15.jpg',
				'aboutBoard' => '',
				'admissionDesc' => '',
				'boardDesc' => '',
				'syllabusDesc' => '',
				'samplePaper' => '',
				'admitCardDetails' => '',
				'preprationTips' => '',
				'resultDesc' => '',
				'entranceExam' => '',
				'chooseRightCollege' => '',
				'counselingBoardId' => 15,
				'created_at' => '2020-04-23 12:26:47',
				'updated_at' => '2020-04-29 10:16:49',
				'employee_id' => 8233,
			),
			15 => 
			array (
				'id' => 16,
				'title' => '',
				'description' => '',
				'image' => 'counseling-boards-bseh-16.jpg',
				'aboutBoard' => '',
				'admissionDesc' => '',
				'boardDesc' => '',
				'syllabusDesc' => '',
				'samplePaper' => '',
				'admitCardDetails' => '',
				'preprationTips' => '',
				'resultDesc' => '',
				'entranceExam' => '',
				'chooseRightCollege' => '',
				'counselingBoardId' => 16,
				'created_at' => '2020-04-23 12:26:49',
				'updated_at' => '2020-04-29 10:16:22',
				'employee_id' => 8233,
			),
			16 => 
			array (
				'id' => 17,
				'title' => '',
				'description' => '',
				'image' => 'counseling-boards-msbshse-17.jpg',
				'aboutBoard' => '',
				'admissionDesc' => '',
				'boardDesc' => '',
				'syllabusDesc' => '',
				'samplePaper' => '',
				'admitCardDetails' => '',
				'preprationTips' => '',
				'resultDesc' => '',
				'entranceExam' => '',
				'chooseRightCollege' => '',
				'counselingBoardId' => 17,
				'created_at' => '2020-04-23 12:26:52',
				'updated_at' => '2020-04-29 10:14:59',
				'employee_id' => 8233,
			),
		));
	}

}
