<?php

use Illuminate\Database\Seeder;

class CourseTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
   	public function run()
    {
        DB::table('course')->delete();

        $course = array(
                array('name' => 'Bachelor of Business Administration  (Human Resource Management)', 'degree_id' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Business Administration  (Marketing)', 'degree_id' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Business Management (BBM)', 'degree_id' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Business Administration  (Accounting and Finance)', 'degree_id' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor in Business Economics (BBE)', 'degree_id' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Arts (Economics)', 'degree_id' => 2, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Arts  (English Literature)', 'degree_id' => 2, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Arts  (Hindi)', 'degree_id' => 2, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Arts  (History)', 'degree_id' => 2, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Arts  (Home Science)', 'degree_id' => 2, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Arts  (Hons.) (Sociology)', 'degree_id' => 2, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Business Administration (MBA)', 'degree_id' => 4, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Dental Science (BDS)', 'degree_id' => 5, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Veterinary Science (BVSC)', 'degree_id' => 7, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Dental Sciences (MDS)', 'degree_id' => 6, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Arts (Philosophy)', 'degree_id' => 2, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Arts  (Political Science)', 'degree_id' => 2, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Veterinary Science (MVSC)', 'degree_id' => 8, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Business Administration (Actuarial Science)', 'degree_id' => 4, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Business Administration  (Biotechnology)', 'degree_id' => 4, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Business Administration  (Business Economics)', 'degree_id' => 4, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Arts  (Psychology)', 'degree_id' => 2, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Business Administration (Energy Management)', 'degree_id' => 4, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Homeopathic Medicine & Surgery (BHMS)', 'degree_id' => 9, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Business Administration (Environmental Management)', 'degree_id' => 4, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Performing Arts (BPA)', 'degree_id' => 2, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Business Administration (Event Management)', 'degree_id' => 4, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Laws (L.L.B.)', 'degree_id' => 10, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Library and Information Science (B.Lib.I.Sc)', 'degree_id' => 2, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Business Administration (Finance)', 'degree_id' => 4, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Arts + Bachelor of Laws [B.A.L.L.B.]', 'degree_id' => 10, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Business Administration (Foreign Trade)', 'degree_id' => 4, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'M.B.B.S.', 'degree_id' => 13, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'L.L.M', 'degree_id' => 11, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Law (L.L.M.) in Intellectual Property and Trade Law', 'degree_id' => 11, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Science (Medicine)', 'degree_id' => 10, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Business Administration (Health Care Administration)', 'degree_id' => 4, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Business Administration  (Hospitality)', 'degree_id' => 4, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Arts (Ancient History)', 'degree_id' => 15, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Surgery (MS) (General Surgery)', 'degree_id' => 16, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Arts (Applied Psychology)', 'degree_id' => 15, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Computer Applications', 'degree_id' => 17, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Arts (Comparative Indian Literature)', 'degree_id' => 15, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Arts (Culture and Media Studies)', 'degree_id' => 15, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Arts (Development Studies)', 'degree_id' => 15, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Arts (Economics)', 'degree_id' => 15, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Business Administration (HRM)', 'degree_id' => 4, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Arts (English Literature)', 'degree_id' => 15, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Computer Applications', 'degree_id' => 18, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Arts (Gender Studies)', 'degree_id' => 15, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Arts (History)', 'degree_id' => 15, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Pharmacy(B.Pharm) + Master of Business Administration (MBA)', 'degree_id' => 19, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Arts (Mathematics)', 'degree_id' => 15, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Business Administration (IT)', 'degree_id' => 4, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Arts (Philosophy)', 'degree_id' => 15, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Business Administration (IB)', 'degree_id' => 4, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Arts (Political Science)', 'degree_id' => 15, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Arts (Psychology)', 'degree_id' => 15, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Arts  (Public Administration)', 'degree_id' => 15, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Pharmacy (M.Pharm)', 'degree_id' => 19, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Business Administration  (Marketing)', 'degree_id' => 4, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Business Administration (OM)', 'degree_id' => 4, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'B.Sc (Agriculture)', 'degree_id' => 35, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Arts  (Social Work)', 'degree_id' => 15, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Arts  (Sociology)', 'degree_id' => 15, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Fine Arts (MFA)', 'degree_id' => 15, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Business Administration (Power Management)', 'degree_id' => 4, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Arts  (Home Science)', 'degree_id' => 15, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Business Administration (Real Estate)', 'degree_id' => 4, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Arts  (Interior Design)', 'degree_id' => 15, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Pharmacy (B.Pharm)', 'degree_id' => 22, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Science (M.Sc) (Agriculture)', 'degree_id' => 31, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Business Administration (Retail Management)', 'degree_id' => 4, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Arts (Film Studies)', 'degree_id' => 15, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Business Administration (Travel & Tourism)', 'degree_id' => 4, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Science [M.Sc] (Dairy Engineering)', 'degree_id' => 31, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Post Graduate Diploma in Retail Management', 'degree_id' => 4, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'B.ARCH', 'degree_id' => 23, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Science (B.Sc) (Nursing)', 'degree_id' => 47, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Post Graduate Diploma in Rural Development', 'degree_id' => 4, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Science (Nursing)', 'degree_id' => 31, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'M.Phil. (Economics)', 'degree_id' => 26, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Architecture [M.Arch.] (Urban & Rural Planning)', 'degree_id' => 27, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'M.Phil. (English Literature)', 'degree_id' => 26, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'M.Phil. (Hindi)', 'degree_id' => 26, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'M.Phil. (Mathematics)', 'degree_id' => 26, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'M.Phil. (Music)', 'degree_id' => 26, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'M.Phil. (Physical Education)', 'degree_id' => 26, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'M.Phil. (Political Science)', 'degree_id' => 26, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master in City and Technology (MaCT)', 'degree_id' => 27, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'M.Phil. (Sociology)', 'degree_id' => 26, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Philosophy (Mechanical Engineering)', 'degree_id' => 26, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'M.Phil (Microbiology)', 'degree_id' => 26, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'M.Phil. (Computer Science)', 'degree_id' => 26, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'M.Phil. (Media Studies)', 'degree_id' => 26, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Ph.D. (Mathematics)', 'degree_id' => 26, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'M.Phil. (Tourism)', 'degree_id' => 26, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'M.Plan', 'degree_id' => 29, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Business Administration  (Executive) (HRM)', 'degree_id' => 28, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'B.SC (AVIATION)', 'degree_id' => 33, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Arts (BA) (Journalism)', 'degree_id' => 30, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'M.SC (AVIATION)', 'degree_id' => 31, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Journalism and Mass Communication (B.J.M.C.)', 'degree_id' => 30, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Science (B.Sc) (Animation & Multimedia)', 'degree_id' => 30, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Arts (M.A.) (Advertising & Public Relations)', 'degree_id' => 33, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Arts (M.A.)  (Journalism)', 'degree_id' => 33, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Business Administration (Executive) (Marketing)', 'degree_id' => 28, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Arts (M.A.)  (Mass Communication)', 'degree_id' => 33, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Business Administration (Executive) (Retail Management)', 'degree_id' => 28, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Business Administration (Executive) (IB)', 'degree_id' => 28, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Business Administration  (Hotel Management)', 'degree_id' => 35, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Hotel Management and Catering Technology (BHMCT)', 'degree_id' => 35, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Business Economics (MBE)', 'degree_id' => 38, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Science (Operational Research)', 'degree_id' => 31, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Arts [BA] (Textile Design)', 'degree_id' => 41, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Science  (Anthropology)', 'degree_id' => 31, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Design (B.Des)', 'degree_id' => 41, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Science (B.Sc) (Interior Design)', 'degree_id' => 41, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor in Fashion Technology', 'degree_id' => 41, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Science  (Biochemistry)', 'degree_id' => 31, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Science (Botany)', 'degree_id' => 31, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Science (Computer Science)', 'degree_id' => 39, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Design (M.Des)', 'degree_id' => 42, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Science (Electronic Science)', 'degree_id' => 39, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Fashion Technology [M.F.Tech]', 'degree_id' => 42, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Science  (Geography)', 'degree_id' => 39, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Science  (Geology)', 'degree_id' => 39, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Science (Life Science)', 'degree_id' => 39, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Science Mathematics)', 'degree_id' => 39, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Science  (Microbiology)', 'degree_id' => 31, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Science  (Zoology)', 'degree_id' => 31, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Science  (Information Technology)', 'degree_id' => 31, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Science (Animation)', 'degree_id' => 31, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Science (Physics)', 'degree_id' => 31, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Science (Applied Mathematics)', 'degree_id' => 43, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Science  (Applied Physics)', 'degree_id' => 43, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Science  (Biochemistry)', 'degree_id' => 31, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Science (Biochemistry)', 'degree_id' => 43, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Science (Biology)', 'degree_id' => 43, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Science (Botany)', 'degree_id' => 43, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Science (Chemistry)', 'degree_id' => 43, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Science (Computer Science)', 'degree_id' => 43, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Science (Economics)', 'degree_id' => 43, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Science (Electronics)', 'degree_id' => 43, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Science  (Life Sciences)', 'degree_id' => 43, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Science (Physical Sciences)', 'degree_id' => 43, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Science (Physics)', 'degree_id' => 43, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Science (Social Sciences)', 'degree_id' => 43, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Science (Statistics)', 'degree_id' => 43, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Technology  (Chemical Engineering)', 'degree_id' => 44, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Technology (Civil Engineering)', 'degree_id' => 44, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Technology  (Agricultural Engineering)', 'degree_id' => 44, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Technology (Automobile Engineering)', 'degree_id' => 44, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Technology (Biomedical Engineering)', 'degree_id' => 44, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Technology  (Biotechnology)', 'degree_id' => 44, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Technology  (Chemical Science and Technology)', 'degree_id' => 44, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Technology  (Computer Science)', 'degree_id' => 44, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Technology  (Computer  Engineering)', 'degree_id' => 44, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Technology (Computer Science and Engineering)', 'degree_id' => 44, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Technology (Electrical and Electronics Engineering)', 'degree_id' => 44, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Technology (Electrical Engineering)', 'degree_id' => 44, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Technology (Electronics & Communication)', 'degree_id' => 44, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Technology (Electronics & Media Technology)', 'degree_id' => 44, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Technology  (Electronics Engineering)', 'degree_id' => 44, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Technology  (Engineering Physics)', 'degree_id' => 44, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Technology (Environmental Engineering)', 'degree_id' => 44, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Technology  (Food Technology)', 'degree_id' => 44, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Technology (Industrial & Production Engineering)', 'degree_id' => 44, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Technology (Instrumentation & Control Engineering)', 'degree_id' => 44, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Technology (Marine Engineering)', 'degree_id' => 44, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Technology (Mechanical Engineering)', 'degree_id' => 44, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Technology  (Mining)', 'degree_id' => 44, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Technology  (Nanotechnology)', 'degree_id' => 44, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Technology  (Polymer Engineering)', 'degree_id' => 44, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Technology (Polymer Technology)', 'degree_id' => 44, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Technology (Power Engineering)', 'degree_id' => 44, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Technology (Printing Technology)', 'degree_id' => 44, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Technology  (Production Engineering)', 'degree_id' => 44, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Technology (Software Engineering)', 'degree_id' => 44, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Technology (Telecommunication Engineering)', 'degree_id' => 44, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Technology  (Textile Engineering)', 'degree_id' => 44, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Technology (Petrochemical Technology)', 'degree_id' => 44, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Technology (Textile Chemistry)', 'degree_id' => 44, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Technology (Bioinformatics)', 'degree_id' => 44, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Technology (Computer and Information Science)', 'degree_id' => 44, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Technology  (Food Science)', 'degree_id' => 44, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Technology  (Information Technology)', 'degree_id' => 44, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Technology (Dairy Technology)', 'degree_id' => 44, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Technology (Urban & Regional Planning)', 'degree_id' => 44, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Technology  (Fashion Technology', 'degree_id' => 44, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Technology  (Electronics and Nanotechnology)', 'degree_id' => 44, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Technology  (Manufacturing Engineering)', 'degree_id' => 44, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Technology (Metallurgical and Materials Engineering)', 'degree_id' => 44, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Technology  (Food Process Engineering)', 'degree_id' => 44, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Technology (Industrial Design)', 'degree_id' => 44, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Technology (Print & Media Technology)', 'degree_id' => 44, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Technology (Information Security)', 'degree_id' => 44, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Technology (Cyber Security)', 'degree_id' => 44, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Engineering [BE] (Nanotechnology)', 'degree_id' => 44, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Technology  (Civil Engineering)', 'degree_id' => 45, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Technology (Aeronautical Engineering)', 'degree_id' => 45, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Technology (Aerospace Engineering)', 'degree_id' => 45, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Technology  (Agricultural Engineering)', 'degree_id' => 45, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Technology (Automobile Engineering)', 'degree_id' => 45, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Technology (Biotechnology)', 'degree_id' => 45, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Technology  (Chemical Engineering)', 'degree_id' => 45, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Technology  (Electrical and Electronics Engineering)', 'degree_id' => 45, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Technology (Electronics & Telecommunications Engineering)', 'degree_id' => 45, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Technology (Electronics and Instrumentation Engineering)', 'degree_id' => 45, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Technology (Electronics Engineering)', 'degree_id' => 45, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Technology (Energy Engineering)', 'degree_id' => 45, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Technology (Food Biotechnology)', 'degree_id' => 45, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Technology (Food Process Engineering)', 'degree_id' => 45, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Technology (Information Technology)', 'degree_id' => 45, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Technology (Marine Engineering)', 'degree_id' => 45, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Technology  (Mechanical Engineering)', 'degree_id' => 45, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Technology (Mining Engineering)', 'degree_id' => 45, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Technology (Software Engineering)', 'degree_id' => 45, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Technology (Computer Science)', 'degree_id' => 45, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Technology (Manufacturing Engineering)', 'degree_id' => 45, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Post Graduate Diploma in Management (PGDM)', 'degree_id' => 46, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Commerce (B.Com)', 'degree_id' => 40, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'B.Sc (Agriculture) ', 'degree_id' => 43, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'M.Sc (Aviation)', 'degree_id' => 39, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'M.Sc (Medicine)', 'degree_id' => 39, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'M.Sc (Nursing)', 'degree_id' => 39, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'B.Sc (Aviation)', 'degree_id' => 43, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'B.Sc (Agriculture)', 'degree_id' => 43, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'B.Sc (Nursing)', 'degree_id' => 43, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'BA (Economics)', 'degree_id' => 2, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'M.Sc (Agriculture)', 'degree_id' => 39, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'B.Sc (Yoga)', 'degree_id' => 43, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'B.Sc (Medical)', 'degree_id' => 43, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'B.Sc (Non Medical)', 'degree_id' => 43, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'B.Ed', 'degree_id' => 34, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Diploma in Education (D.Ed)', 'degree_id' => 52, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Diploma in Mechanical Engineering (DME)', 'degree_id' => 48, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Diploma in Civil Engineering', 'degree_id' => 48, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Diploma in Electronics And Communication Engineering ', 'degree_id' => 48, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Diploma in  Computer Science', 'degree_id' => 48, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'B.Pharmacy', 'degree_id' => 22, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of pharmacy', 'degree_id' => 22, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Diploma Electrical ', 'degree_id' => 48, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Diploma Electronics  ', 'degree_id' => 48, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Diploma in Civil Engineering', 'degree_id' => 48, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Diploma Computer Science ', 'degree_id' => 49, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Technology (Printing & Packaging Technology)', 'degree_id' => 44, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Technology (Electronics & Communication Engineering)', 'degree_id' => 45, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Technology (Electrical Engineering)', 'degree_id' => 45, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'M.ARCH', 'degree_id' => 27, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'M.ARCH', 'degree_id' => 54, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Technology (Computer Science and Engineering)', 'degree_id' => 45, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Technology (Digital Communication)', 'degree_id' => 45, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Technology (Heat Power and Thermal Engineering)', 'degree_id' => 45, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Technology (Computer Technology and  Applications)', 'degree_id' => 45, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Technology (Micro Electronics and VLSI Design)', 'degree_id' => 45, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Technology (Power Electonics)', 'degree_id' => 45, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Technology (Power System)', 'degree_id' => 45, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Diploma (Mechanical Automobile)', 'degree_id' => 48, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of commerce ( Advanced Business Statistics)', 'degree_id' => 38, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Commerce (Business Add)', 'degree_id' => 38, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Pharmacy (Pharmaceutical Chemistry)', 'degree_id' => 19, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Pharmacy (Pharmaceutics)', 'degree_id' => 19, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Pharmacy (Pharmacology)', 'degree_id' => 19, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of  Pharmacy (Pharmaceutical Science)', 'degree_id' => 22, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Pharmacy (Pharmaceutical Analysis)', 'degree_id' => 19, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'D.Pharma', 'degree_id' => 55, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Technology (Instrumentation and Control Engineering)', 'degree_id' => 45, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Technology (Production and Industrial System)', 'degree_id' => 45, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Technology (Communication Control and Network)', 'degree_id' => 45, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Technology (Thermal Engineering)', 'degree_id' => 45, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Post Graduate Diploma in Management (Health care and Hospital Management)', 'degree_id' => 46, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Art (Geography)', 'degree_id' => 15, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'DCA', 'degree_id' => 56, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'PGDCA', 'degree_id' => 57, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Science (Medical Laboratory Technology)', 'degree_id' => 43, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'BSc MIT - Bachelor of Science in Medical Imaging Technology', 'degree_id' => 43, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'BSc RT - Bachelor of Science in Respiratory Therapy', 'degree_id' => 43, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'BSc NMT - Bachelor of Science in Nuclear Medicine Technology', 'degree_id' => 43, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'BSc HIA - Bachelor of Science in Health Information Administration', 'degree_id' => 43, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Diploma in Medical Laboratoty Technology', 'degree_id' => 58, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Diploma in Electrical and Electronics', 'degree_id' => 48, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Diploma in Medical Laboratory Technician (DMLT)', 'degree_id' => 59, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Diploma in X-Ray Technician (X-RAY)', 'degree_id' => 59, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Diploma in ECG Technology (ECG/EEG)', 'degree_id' => 59, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bio-madical Instrumentation', 'degree_id' => 59, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Diploma in Operation Theater (OT)', 'degree_id' => 59, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Diploma in Mining Engineering', 'degree_id' => 48, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Diploma in Architecture', 'degree_id' => 48, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Mechanical Engineering (Automobile)', 'degree_id' => 48, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Mechanical Engineering (Production)', 'degree_id' => 48, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Post Graduate Diploma In Business Management (PGDBM)', 'degree_id' => 61, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Post Graduate Diploma in Import & Export Management (PGDIEM)', 'degree_id' => 60, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Post Graduate Diploma in Foreign Trade (PGDFT)', 'degree_id' => 61, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Post Graduate Diploma in Marketing Management (PGDMM)', 'degree_id' => 61, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Post Graduate Diploma in Materials and Logistics Management (PGDMLM)', 'degree_id' => 61, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Post Graduate Diploma in Financial Services (PGDFS)', 'degree_id' => 51, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Metallurgical Engineering', 'degree_id' => 48, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Instrumentation & Control Engineering', 'degree_id' => 48, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Quality Assurance', 'degree_id' => 19, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Diploma (Information Technology)', 'degree_id' => 48, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'PGDM (Human Resource and Management)', 'degree_id' => 60, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'PGDM (Rural Management)', 'degree_id' => 46, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'PGDM (Information Technology)', 'degree_id' => 46, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'PGDM (Finance)', 'degree_id' => 46, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'PGDM (Marketing)', 'degree_id' => 46, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'B.Sc. In Hospitality studies', 'degree_id' => 35, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'ASP.NET', 'degree_id' => 62, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Diploma in Plastic Technology', 'degree_id' => 48, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Diploma in Chemical Engineering', 'degree_id' => 48, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Diploma in Marine Engineering', 'degree_id' => 48, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Technology (Geo Technical Energy)', 'degree_id' => 45, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Technology (Reneval Energy)', 'degree_id' => 45, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Clinical Data Management', 'degree_id' => 63, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Advanced Post Graduate Diploma in Regulatory Affairs', 'degree_id' => 64, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Diploma in Business Management', 'degree_id' => 65, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Executive Diploma in Export Management (EDEM)', 'degree_id' => 65, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Diploma in Entrepreneurship Management', 'degree_id' => 65, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'M.Ed', 'degree_id' => 36, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => ' Finance Specialization', 'degree_id' => 67, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Marketing Specialization', 'degree_id' => 67, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'MMS (Information Technology Specialization)', 'degree_id' => 67, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'General Nursing and Midwifery (GNM)', 'degree_id' => 68, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => ' Auxiliary Nursing Midwifery (ANM)', 'degree_id' => 68, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Post Basic B.Sc (Nursing)', 'degree_id' => 69, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Anuimation , VFX ,Gaming and Comics', 'degree_id' => 50, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Cyber Security/ IT Security', 'degree_id' => 50, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelors in Hospitality Studies', 'degree_id' => 70, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Hotel Operation', 'degree_id' => 70, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Certificate course in Cookery  Bakery and confectionary', 'degree_id' => 71, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Pharmacy (Bio Technology)', 'degree_id' => 19, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Technology (Construction Technology and Management)', 'degree_id' => 45, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Pharmacy (Pharmacognosy)', 'degree_id' => 19, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Pharmacy (Pharmaceutical Biotechnology)', 'degree_id' => 19, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Ayurved Nursing and Pharmacy', 'degree_id' => 72, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'FINANCE ', 'degree_id' => 46, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Supply chain & operation Management', 'degree_id' => 46, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'HUMAN RESOURCE MANAGEMENT', 'degree_id' => 46, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Diploma in Nutrition and Dietics', 'degree_id' => 73, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor in Physiotherpy (BPT)', 'degree_id' => 74, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Physiotherpy', 'degree_id' => 74, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'BBA (Mass Communication)', 'degree_id' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'BBA (Adevertising and Public Relation)', 'degree_id' => 1, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Science (Electronic Media)', 'degree_id' => 43, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'LSA (now Animal Husbandary Diploma)', 'degree_id' => 75, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Science (IT)', 'degree_id' => 39, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Post Graduate Diploma in Event Mgmt. and Activation', 'degree_id' => 46, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Post Graduate Diploma In Event Mgmt.', 'degree_id' => 46, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Diploma in Event Mgmt.', 'degree_id' => 65, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'B.P.Ed', 'degree_id' => 33, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor in Computer Science (B.Sc)', 'degree_id' => 76, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Science  (IT)', 'degree_id' => 43, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Diploma in Electronics and Telecommunication', 'degree_id' => 48, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'PGDM (Business Management)', 'degree_id' => 46, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Aircraft Maintenance Engineering (AME)', 'degree_id' => 77, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'PGDM (General Management)', 'degree_id' => 46, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Private Pilot License (PPL)', 'degree_id' => 78, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => ' PGDM (Global Business Management)', 'degree_id' => 46, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'PGPM', 'degree_id' => 79, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'B.Com (Hons)', 'degree_id' => 40, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master diploma in Emergency Medical Services', 'degree_id' => 81, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Emergency medical Services (Basic)', 'degree_id' => 82, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Diploma in Science and Humanities', 'degree_id' => 48, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'MBA (Banking and Insurance Management)', 'degree_id' => 4, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'MBA (Corporate Management)', 'degree_id' => 4, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'M.Sc (Computer Application)', 'degree_id' => 39, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'M.P.Ed', 'degree_id' => 37, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'B.Sc. (Bio-Technology)', 'degree_id' => 43, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Master of Technology (VLSI DESIGN)', 'degree_id' => 45, 'created_at' => new DateTime,'updated_at' => new DateTime,),
                array('name' => 'Bachelor of Technology ( Information Technology)', 'degree_id' => 44, 'created_at' => new DateTime,'updated_at' => new DateTime,),

        );

        DB::table('course')->insert( $course );
    }
}
