<?php

use Illuminate\Database\Seeder;

class SeoContentTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('seo_contents')->delete();
        $seo_contents = array(
        	array(
                'pagetitle'      => 'About Us',
                'misc'           => 'about-us',
                'pageId'	     => '1',
                'created_at'     => new DateTime,
                'updated_at'     => new DateTime,
            ),
            array(
                'pagetitle'      => 'Admission Registration Policy',
                'misc'           => 'admission-registration-policy',
                'pageId'	     => '2',
                'created_at'     => new DateTime,
                'updated_at'     => new DateTime,
            ),
            array(
                'pagetitle'      => 'Advertiser Agreement',
                'misc'           => 'advertiser-agreement',
                'pageId'          => '3',
                'created_at'     => new DateTime,
                'updated_at'     => new DateTime,
            ),
            array(
                'pagetitle'      => 'Cancellation Refunds',
                'misc'           => 'cancellation-refunds',
                'pageId'          => '4',
                'created_at'     => new DateTime,
                'updated_at'     => new DateTime,
            ),
            array(
                'pagetitle'      => 'College Partner Agreement',
                'misc'           => 'college-partner-agreement',
                'pageId'	     => '5',
                'created_at'     => new DateTime,
                'updated_at'     => new DateTime,
            ),
            array(
                'pagetitle'      => 'Contact Us',
                'misc'           => 'contact-us',
                'pageId'	     => '6',
                'created_at'     => new DateTime,
                'updated_at'     => new DateTime,
            ),
            array(
                'pagetitle'      => 'Disclaimer',
                'misc'           => 'disclaimer',
                'pageId'	     => '7',
                'created_at'     => new DateTime,
                'updated_at'     => new DateTime,
            ),
            array(
                'pagetitle'      => 'Counselling Page',
                'misc'           => 'counselling',
                'pageId'	     => '8',
                'created_at'     => new DateTime,
                'updated_at'     => new DateTime,
            ),
            array(
                'pagetitle'      => 'Payments Terms Of Service',
                'misc'           => 'payments-terms-of-service',
                'pageId'          => '9',
                'created_at'     => new DateTime,
                'updated_at'     => new DateTime,
            ),
            array(
                'pagetitle'      => 'Policies',
                'misc'           => 'policies',
                'pageId'	     => '10',
                'created_at'     => new DateTime,
                'updated_at'     => new DateTime,
            ),
            array(
                'pagetitle'      => 'Press',
                'misc'           => 'press',
                'pageId'          => '11',
                'created_at'     => new DateTime,
                'updated_at'     => new DateTime,
            ),
            array(
                'pagetitle'      => 'Privacy Policy',
                'misc'           => 'privacy-policy',
                'pageId'	     => '12',
                'created_at'     => new DateTime,
                'updated_at'     => new DateTime,
            ),
            array(
                'pagetitle'      => 'Student Referral Policy',
                'misc'           => 'student-referral-policy',
                'pageId'          => '13',
                'created_at'     => new DateTime,
                'updated_at'     => new DateTime,
            ),
            array(
                'pagetitle'      => 'Terms Of Service',
                'misc'           => 'terms-of-service',
                'pageId'	     => '14',
                'created_at'     => new DateTime,
                'updated_at'     => new DateTime,
            ),
            array(
                'pagetitle'      => 'Terms and Privacy',
                'misc'           => 'terms-and-privacy',
                'pageId'	     => '15',
                'created_at'     => new DateTime,
                'updated_at'     => new DateTime,
            ),
            array(
                'pagetitle'      => 'Terms & Conditions',
                'misc'           => 'terms-and-conditions',
                'pageId'	     => '16',
                'created_at'     => new DateTime,
                'updated_at'     => new DateTime,
            ),
            array(
                'pagetitle'      => 'Trust and Safety',
                'misc'           => 'trust-and-safety',
                'pageId'          => '17',
                'created_at'     => new DateTime,
                'updated_at'     => new DateTime,
            ),
            array(
                'pagetitle'      => 'Home Page',
                'misc'           => 'home-page',
                'pageId'         => null,
                'created_at'     => new DateTime,
                'updated_at'     => new DateTime,
            ),
            array(
                'pagetitle'      => 'Blog Page',
                'misc'           => 'blog-page',
                'pageId'	     => null,
                'created_at'     => new DateTime,
                'updated_at'     => new DateTime,
            ),
            array(
                'pagetitle'      => 'Careers',
                'misc'           => 'careers',
                'pageId'	     => null,
                'created_at'     => new DateTime,
                'updated_at'     => new DateTime,
            ),
            array(
                'pagetitle'      => 'Testimonial Page',
                'misc'           => 'testimonial-page',
                'pageId'	     => null,
                'created_at'     => new DateTime,
                'updated_at'     => new DateTime,
            ),
            array(
                'pagetitle'      => 'Login Page',
                'misc'           => 'login-page',
                'pageId'	     => null,
                'created_at'     => new DateTime,
                'updated_at'     => new DateTime,
            ),
            array(
                'pagetitle'      => 'Registration Page',
                'misc'           => 'registration-page',
                'pageId'	     => null,
                'created_at'     => new DateTime,
                'updated_at'     => new DateTime,
            ),
            array(
                'pagetitle'      => 'College Signup',
                'misc'           => 'college-signup',
                'pageId'	     => null,
                'created_at'     => new DateTime,
                'updated_at'     => new DateTime,
            ),
            array(
                'pagetitle'      => 'Update Password',
                'misc'           => 'update-password',
                'pageId'	     => null,
                'created_at'     => new DateTime,
                'updated_at'     => new DateTime,
            ),
            array(
                'pagetitle'      => 'Search Page',
                'misc'           => 'search-page',
                'pageId'         => null,
                'created_at'     => new DateTime,
                'updated_at'     => new DateTime,
            ),
            array(
                'pagetitle'      => '404 Page',
                'misc'           => '404-page',
                'pageId'         => null,
                'created_at'     => new DateTime,
                'updated_at'     => new DateTime,
            ),
            array(
                'pagetitle'      => 'Quick Signup Page',
                'misc'           => 'quick-signup-page',
                'pageId'         => null,
                'created_at'     => new DateTime,
                'updated_at'     => new DateTime,
            ),
            array(
                'pagetitle'      => 'Board List Page',
                'misc'           => 'board-list-page',
                'pageId'         => null,
                'created_at'     => new DateTime,
                'updated_at'     => new DateTime,
            ),
            array(
                'pagetitle'      => 'Course List Page',
                'misc'           => 'course-list-page',
                'pageId'         => null,
                'created_at'     => new DateTime,
                'updated_at'     => new DateTime,
            ),
            array(
                'pagetitle'      => 'Popular Careers',
                'misc'           => 'popular-careers',
                'pageId'         => null,
                'created_at'     => new DateTime,
                'updated_at'     => new DateTime,
            ),
            array(
                'pagetitle'      => 'Sitemap',
                'misc'           => 'sitemap',
                'pageId'         => null,
                'created_at'     => new DateTime,
                'updated_at'     => new DateTime,
            ),
            array(
                'pagetitle'      => 'Engineering Association Examination',
                'misc'           => 'engineering-association-examination',
                'pageId'         => null,
                'created_at'     => new DateTime,
                'updated_at'     => new DateTime,
            ),
            array(
                'pagetitle'      => 'Reviews',
                'misc'           => 'review-page',
                'pageId'         => null,
                'created_at'     => new DateTime,
                'updated_at'     => new DateTime,
            ),
            array(
                'pagetitle'      => 'Top College List Page',
                'misc'           => 'top-college-list-page',
                'pageId'         => null,
                'created_at'     => new DateTime,
                'updated_at'     => new DateTime,
            ),
            array(
                'pagetitle'      => 'Top University List Page',
                'misc'           => 'top-university-list-page',
                'pageId'         => null,
                'created_at'     => new DateTime,
                'updated_at'     => new DateTime,
            ),
            array(
                'pagetitle'      => 'Top Course List Page',
                'misc'           => 'top-course-list-page',
                'pageId'         => null,
                'created_at'     => new DateTime,
                'updated_at'     => new DateTime,
            ),
            array(
                'pagetitle'      => 'Latest Update Page',
                'misc'           => 'latest-update-page',
                'pageId'         => null,
                'created_at'     => new DateTime,
                'updated_at'     => new DateTime,
            ),
            array(
                'pagetitle'      => 'Study Abroad Page',
                'misc'           => 'study-abroad-page',
                'pageId'         => null,
                'created_at'     => new DateTime,
                'updated_at'     => new DateTime,
            ),
            array(
                'pagetitle'      => 'Stream List Page',
                'misc'           => 'stream-list-page',
                'pageId'         => null,
                'created_at'     => new DateTime,
                'updated_at'     => new DateTime,
            ),
            array(
                'pagetitle'      => 'Stream Degree List Page',
                'misc'           => 'stream-degree-list-page',
                'pageId'         => null,
                'created_at'     => new DateTime,
                'updated_at'     => new DateTime,
            ),
            array(
                'pagetitle'      => 'Degree Course List Page',
                'misc'           => 'degree-course-list-page',
                'pageId'         => null,
                'created_at'     => new DateTime,
                'updated_at'     => new DateTime,
            ),
            array(
                'pagetitle'      => 'Examination Page',
                'misc'           => 'examination-page',
                'pageId'         => null,
                'created_at'     => new DateTime,
                'updated_at'     => new DateTime,
            ),
            array(
                'pagetitle'      => 'Examination Search Page',
                'misc'           => 'examination-search-page',
                'pageId'         => null,
                'created_at'     => new DateTime,
                'updated_at'     => new DateTime,
            ),
            array(
                'pagetitle'      => 'Careers Opportunities List Page',
                'misc'           => 'careers-opportunities-list-page',
                'pageId'         => null,
                'created_at'     => new DateTime,
                'updated_at'     => new DateTime,
            ),
            array(
                'pagetitle'      => 'Careers Opportunities Intrest Page',
                'misc'           => 'careers-opportunities-intrest-page',
                'pageId'         => null,
                'created_at'     => new DateTime,
                'updated_at'     => new DateTime,
            ),
            array(
                'pagetitle'      => 'Careers Opportunities Relevant Page',
                'misc'           => 'careers-opportunities-relevant-page',
                'pageId'         => null,
                'created_at'     => new DateTime,
                'updated_at'     => new DateTime,
            ),
            array(
                'pagetitle'      => 'News Page',
                'misc'           => 'news-page',
                'pageId'         => null,
                'created_at'     => new DateTime,
                'updated_at'     => new DateTime,
            ),
            array(
                'pagetitle'      => 'News Type List',
                'misc'           => 'news-type-list',
                'pageId'         => NULL,
                'created_at'     => new DateTime,
                'updated_at'     => new DateTime,
            ),
            array(
                'pagetitle'      => 'News Tags List',
                'misc'           => 'news-tags-list',
                'pageId'         => NULL,
                'created_at'     => new DateTime,
                'updated_at'     => new DateTime,
            ),
            array(
                'pagetitle'      => 'Ask',
                'misc'           => 'ask-page',
                'pageId'         => null,
                'created_at'     => new DateTime,
                'updated_at'     => new DateTime,
            ),
            array(
                'pagetitle'      => 'Ask Question Tags List',
                'misc'           => 'ask-question-tags-list',
                'pageId'         => NULL,
                'created_at'     => new DateTime,
                'updated_at'     => new DateTime,
            ),
            array(
                'pagetitle'      => 'Help Center',
                'misc'           => 'help-center',
                'pageId'         => NULL,
                'created_at'     => new DateTime,
                'updated_at'     => new DateTime,
            ),
        );
        DB::table('seo_contents')->insert( $seo_contents );
    }
}