INSERT INTO topstream (name, pageslug, created_at, updated_at) VALUES 
('Engineering', 'engineering', NOW(), NOW()),
('Arts', 'arts', NOW(), NOW()),
('Mass Communication & Media', 'mass-communication-media', NOW(), NOW()),
('Education & Languages', 'education-languages', NOW(), NOW()),
('Commerce', 'commerce', NOW(), NOW()),
('Management', 'management', NOW(), NOW()),
('Hotel Management', 'hotel-management', NOW(), NOW()),
('Science', 'science', NOW(), NOW()),
('Dental', 'dental', NOW(), NOW()),
('Medical', 'medical', NOW(), NOW()),
('Pharmacy', 'pharmacy', NOW(), NOW()),
('Paramedical', 'paramedical', NOW(), NOW()),
('Veterinary Sciences', 'veterinary-sciences', NOW(), NOW()),
('Law', 'law', NOW(), NOW()),
('Computer Applications', 'computer-applications', NOW(), NOW()),
('Agriculture', 'agriculture', NOW(), NOW()),
('Architecture', 'architecture', NOW(), NOW()),
('Aviation', 'aviation', NOW(), NOW()),
('Design', 'design', NOW(), NOW()),
('Tourism', 'tourism', NOW(), NOW()),
('Beauty & Healthcare', 'beauty-healthcare', NOW(), NOW()),
('Diploma in Pharmacy', 'diploma-in-pharmacy', NOW(), NOW()),
('Clinical', 'clinical', NOW(), NOW()),
('Professional Teaching', 'professional-teaching', NOW(), NOW()),
('Retail', 'retail', NOW(), NOW()),
('Finance', 'finance', NOW(), NOW()),
('Polytechnic', 'polytechnic', NOW(), NOW()),
('Ph.D', 'phd', NOW(), NOW()),
('Ayurveda', 'ayurveda', NOW(), NOW()),
('Photography', 'photography', NOW(), NOW()),
('Sea Training', 'sea-training', NOW(), NOW()),
('Business Analyitcs', 'business-analyitcs', NOW(), NOW()),
('Counselling', 'counselling', NOW(), NOW()),
('Music', 'music', NOW(), NOW()),
('Engineering and Management', 'engineering-and-management', NOW(), NOW()),
('Gymnasium', 'gymnasium', NOW(), NOW()),
('Forestry', 'forestry', NOW(), NOW()),
('Dance', 'dance', NOW(), NOW()),
('Philosophy', 'philosophy', NOW(), NOW()),
('Drawing', 'drawing', NOW(), NOW()),
('Navy / Army', 'navy-army', NOW(), NOW()),
('Air Hostess Training / Flight Attendant Training', 'air-hostess-training-flight-attendant-training', NOW(), NOW()),
('Astronomy', 'astronomy', NOW(), NOW()),
('Medicine', 'medicine', NOW(), NOW()),
('Business', 'business', NOW(), NOW()),
('After - Diploma', 'after-diploma', NOW(), NOW()),
('After - Post Graduate Diploma', 'after-post-graduate-diploma', NOW(), NOW()),
('After - Certification Course', 'after-certification-course', NOW(), NOW()),
('After - Doctor of Philosophy', 'after-doctor-of-philosophy', NOW(), NOW()),
('After - Master Degree', 'after-master-degree', NOW(), NOW()),
('After - Bachelor Degree', 'after-bachelor-degree', NOW(), NOW()),
('After - Fast-Track', 'after-fast-track', NOW(), NOW());
