INSERT INTO blogs (users_id, topic, description, featimage, isactive, slug, created_at, updated_at) VALUES 
(7, 'Top 10 Engineering Colleges in India 2024', 'Discover the best engineering colleges in India offering world-class education, excellent placements, and state-of-the-art facilities. Learn about admission process, fees, and career opportunities.', 'engineering-colleges.jpg', 1, 'top-10-engineering-colleges-india-2024', NOW(), NOW()),
(7, 'How to Prepare for JEE Main 2024', 'Complete guide to crack JEE Main exam with effective study strategies, time management tips, and important topics to focus on for securing top ranks.', 'jee-main-preparation.jpg', 1, 'how-to-prepare-jee-main-2024', NOW(), NOW()),
(7, 'MBA Admission Guide: CAT vs GMAT', 'Comprehensive comparison between CAT and GMAT exams for MBA aspirants. Understand which exam suits your career goals and how to prepare effectively.', 'mba-admission-guide.jpg', 1, 'mba-admission-guide-cat-vs-gmat', NOW(), NOW()),
(7, 'Medical Entrance Exams: NEET Preparation Tips', 'Expert tips and strategies to excel in NEET exam. Learn about important topics, study materials, mock tests, and time management for medical aspirants.', 'neet-preparation.jpg', 1, 'medical-entrance-neet-preparation-tips', NOW(), NOW()),
(7, 'Study Abroad: Top Universities in USA', 'Everything you need to know about studying in USA - top universities, admission requirements, scholarships, visa process, and career opportunities.', 'study-abroad-usa.jpg', 1, 'study-abroad-top-universities-usa', NOW(), NOW()),
(7, 'Career Options After 12th Science', 'Explore diverse career paths available for science students including engineering, medical, research, and emerging fields with salary prospects.', 'career-after-12th.jpg', 1, 'career-options-after-12th-science', NOW(), NOW()),
(7, 'Scholarship Opportunities for Indian Students', 'Complete list of scholarships available for Indian students studying in India and abroad. Learn about eligibility criteria and application process.', 'scholarships.jpg', 1, 'scholarship-opportunities-indian-students', NOW(), NOW()),
(7, 'Law Entrance Exams: CLAT Preparation Strategy', 'Detailed guide to prepare for CLAT and other law entrance exams. Understand exam pattern, syllabus, and effective preparation techniques.', 'clat-preparation.jpg', 1, 'law-entrance-clat-preparation-strategy', NOW(), NOW());
