ALTER TABLE `address` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `addresstype` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `ads_managements` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `alltableinformations` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `application` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `applicationstatus` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `applicationstatusmessages` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `application_and_exam_statuses` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `application_modes` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `ask_questions` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `ask_question_answers` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `ask_question_answer_comments` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `ask_question_tags` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `blogs` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `bookmarks` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `bookmarktypeinfos` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `cardtype` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `careers` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `category` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `city` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `collegefacilities` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `collegelog` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `collegemaster` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `collegeprofile` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `collegetype` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `college_admission_important_dateds` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `college_admission_procedures` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `college_cut_offs` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `college_faqs` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `college_management_details` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `college_master_associate_faculties` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `college_reviews` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `college_scholarships` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `college_social_media_links` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `college_sports_activities` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `contentcategory` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `contents` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `counseling_boards` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `counseling_board_admission_dates` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `counseling_board_details` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `counseling_board_exam_dates` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `counseling_board_highlights` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `counseling_board_imp_dates` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `counseling_board_latest_updates` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `counseling_board_sample_papers` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `counseling_board_syllabus` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `counseling_career_details` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `counseling_career_interests` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `counseling_career_job_role_saleries` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `counseling_career_relevants` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `counseling_career_skill_requirements` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `counseling_career_where_to_studies` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `counseling_courses_details` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `counseling_courses_education_levels` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `counseling_courses_job_careers` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `counseling_courses_more_details` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `counseling_courses_more_titles` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `country` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `country-bk` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `course` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `coursetype` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `degree` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `documents` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `educationlevel` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `eligibility_criterias` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `engineeringexams` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `entranceexam` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `event` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `examination_details` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `examination_important_links` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `examination_modes` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `examination_types` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `examtransaction` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `exam_admit_cards` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `exam_analysis_records` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `exam_answer_keys` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `exam_answer_key_events` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `exam_application_fees` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `exam_application_processes` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `exam_counsellings` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `exam_counselling_contacts` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `exam_counselling_dates` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `exam_counselling_forms` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `exam_cut_offs` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `exam_dates` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `exam_eligibilities` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `exam_faqs` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `exam_list_multiple_degrees` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `exam_patterns` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `exam_prepration_tips` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `exam_questions` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `exam_question_answers` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `exam_question_answer_comments` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `exam_results` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `exam_sections` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `exam_syllabus_papers` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `exam_syllabus_paper_marks` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `facilities` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `faculty` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `faculty_departments` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `faculty_experiences` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `faculty_qualifications` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `functionalarea` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `gallery` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `invite` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `landing_page_query_forms` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `latest_updates` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `news` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `news_tags` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `news_types` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `pages` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `paymentstatus` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `placement` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `query` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `request_for_create_college_accounts` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `seo_contents` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `slider_managers` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `socialmanagements` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `state` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `studentmarks` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `studentprofile` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `subscribe` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `templates` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `testimonials` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `transaction` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `type_of_examinations` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `university` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `usergroups` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `userprivileges` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `userrole` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `users` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `userstatus` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `what_we_offers` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE `logs` CHANGE `created_at` `created_at` TIMESTAMP NULL DEFAULT NULL, CHANGE `updated_at` `updated_at` TIMESTAMP NULL DEFAULT NULL;





ALTER TABLE userrole ADD INDEX(id);
ALTER TABLE userstatus ADD INDEX(id);
ALTER TABLE paymentstatus ADD INDEX(id);
ALTER TABLE cardtype ADD INDEX(id);
ALTER TABLE applicationstatus ADD INDEX(id);
ALTER TABLE category ADD INDEX(id);
ALTER TABLE country ADD INDEX(id);
ALTER TABLE educationlevel ADD INDEX(id);
ALTER TABLE facilities ADD INDEX(id);
ALTER TABLE state ADD INDEX(id);
ALTER TABLE state ADD INDEX(id);
ALTER TABLE university ADD INDEX(id);
ALTER TABLE addresstype ADD INDEX(id);
ALTER TABLE city ADD INDEX(state_id);
ALTER TABLE collegetype ADD INDEX(id);
ALTER TABLE functionalarea ADD INDEX(id);
ALTER TABLE users ADD INDEX(id);
ALTER TABLE users ADD INDEX(employee_id);
ALTER TABLE users ADD INDEX(userstatus_id);
ALTER TABLE users ADD INDEX(userrole_id);
ALTER TABLE collegeprofile ADD INDEX(id);
ALTER TABLE collegeprofile ADD INDEX(employee_id);
ALTER TABLE collegeprofile ADD INDEX(users_id);
ALTER TABLE collegeprofile ADD INDEX(university_id);
ALTER TABLE collegeprofile ADD INDEX(collegetype_id);
ALTER TABLE collegeprofile ADD INDEX(review);
ALTER TABLE collegeprofile ADD INDEX(agreement);
ALTER TABLE collegeprofile ADD INDEX(verified);
ALTER TABLE degree ADD INDEX(functionalarea_id);
ALTER TABLE studentprofile ADD INDEX(id);
ALTER TABLE studentprofile ADD INDEX(isverifiedage);
ALTER TABLE studentprofile ADD INDEX(employee_id);
ALTER TABLE studentprofile ADD INDEX(users_id);
ALTER TABLE collegefacilities ADD INDEX(id);
ALTER TABLE collegefacilities ADD INDEX(employee_id);
ALTER TABLE collegefacilities ADD INDEX(collegeprofile_id);
ALTER TABLE collegefacilities ADD INDEX(facilities_id);
ALTER TABLE coursetype ADD INDEX(id);
ALTER TABLE event ADD INDEX(id);
ALTER TABLE event ADD INDEX(employee_id);
ALTER TABLE event ADD INDEX(collegeprofile_id);
ALTER TABLE studentmarks ADD INDEX(id);
ALTER TABLE studentmarks ADD INDEX(employee_id);
ALTER TABLE studentmarks ADD INDEX(category_id);
ALTER TABLE studentmarks ADD INDEX(studentprofile_id);
ALTER TABLE address ADD INDEX(id);
ALTER TABLE address ADD INDEX(employee_id);
ALTER TABLE address ADD INDEX(addresstype_id);
ALTER TABLE address ADD INDEX(city_id);
ALTER TABLE address ADD INDEX(studentprofile_id);
ALTER TABLE address ADD INDEX(collegeprofile_id);
ALTER TABLE blogs ADD INDEX(id);
ALTER TABLE blogs ADD INDEX(isactive);
ALTER TABLE blogs ADD INDEX(slug);
ALTER TABLE blogs ADD INDEX(employee_id);
ALTER TABLE blogs ADD INDEX(users_id);
ALTER TABLE bookmarks ADD INDEX(id);
ALTER TABLE bookmarks ADD INDEX(student_id);
ALTER TABLE bookmarks ADD INDEX(college_id);
ALTER TABLE bookmarks ADD INDEX(course_id);
ALTER TABLE bookmarks ADD INDEX(blog_id);
ALTER TABLE bookmarks ADD INDEX(employee_id);
ALTER TABLE course ADD INDEX(id);
ALTER TABLE course ADD INDEX(degree_id);
ALTER TABLE course ADD INDEX(employee_id);
ALTER TABLE invite ADD INDEX(id);
ALTER TABLE invite ADD INDEX(isactive);
ALTER TABLE invite ADD INDEX(employee_id);
ALTER TABLE invite ADD INDEX(users_id);
ALTER TABLE application ADD INDEX(id);
ALTER TABLE application ADD INDEX(employee_id);
ALTER TABLE application ADD INDEX(applicationstatus_id);
ALTER TABLE application ADD INDEX(users_id);
ALTER TABLE application ADD INDEX(collegeprofile_id);
ALTER TABLE documents ADD INDEX(id);
ALTER TABLE documents ADD INDEX(employee_id);
ALTER TABLE documents ADD INDEX(category_id);
ALTER TABLE documents ADD INDEX(users_id);
ALTER TABLE gallery ADD INDEX(id);
ALTER TABLE gallery ADD INDEX(employee_id);
ALTER TABLE gallery ADD INDEX(category_id);
ALTER TABLE gallery ADD INDEX(users_id);
ALTER TABLE logs ADD INDEX(id);
ALTER TABLE logs ADD INDEX(users_id);
ALTER TABLE logs ADD INDEX(userrole_id);
ALTER TABLE logs ADD INDEX(employee_id);
ALTER TABLE query ADD INDEX(id);
ALTER TABLE query ADD INDEX(admin_id);
ALTER TABLE query ADD INDEX(college_id);
ALTER TABLE query ADD INDEX(student_id);
ALTER TABLE query ADD INDEX(employee_id);
ALTER TABLE collegemaster ADD INDEX(id);
ALTER TABLE collegemaster ADD INDEX(employee_id);
ALTER TABLE collegemaster ADD INDEX(collegeprofile_id);
ALTER TABLE collegemaster ADD INDEX(educationlevel_id);
ALTER TABLE collegemaster ADD INDEX(functionalarea_id);
ALTER TABLE collegemaster ADD INDEX(degree_id);
ALTER TABLE collegemaster ADD INDEX(coursetype_id);
ALTER TABLE collegemaster ADD INDEX(course_id);
ALTER TABLE transaction ADD INDEX(id);
ALTER TABLE transaction ADD INDEX(employee_id);
ALTER TABLE transaction ADD INDEX(paymentstatus_id);
ALTER TABLE transaction ADD INDEX(cardtype_id);
ALTER TABLE transaction ADD INDEX(application_id);
ALTER TABLE subscribe ADD INDEX(id);
ALTER TABLE subscribe ADD INDEX(employee_id);
ALTER TABLE placement ADD INDEX(id);
ALTER TABLE placement ADD INDEX(employee_id);
ALTER TABLE placement ADD INDEX(collegeprofile_id);
ALTER TABLE pages ADD INDEX(id);
ALTER TABLE pages ADD INDEX(slug);
ALTER TABLE pages ADD INDEX(employee_id);
ALTER TABLE entranceexam ADD INDEX(id);
ALTER TABLE entranceexam ADD INDEX(employee_id);
ALTER TABLE faculty ADD INDEX(id);
ALTER TABLE faculty ADD INDEX(collegemaster_id);
ALTER TABLE faculty ADD INDEX(collegeprofile_id);
ALTER TABLE faculty ADD INDEX(employee_id);
ALTER TABLE alltableinformations ADD INDEX(id);
ALTER TABLE alltableinformations ADD INDEX(employee_id);
ALTER TABLE userprivileges ADD INDEX(id);
ALTER TABLE userprivileges ADD INDEX(allTableInformation_id);
ALTER TABLE userprivileges ADD INDEX(employee_id);
ALTER TABLE userprivileges ADD INDEX(users_id);
ALTER TABLE documents ADD INDEX(application_id);
ALTER TABLE careers ADD INDEX(id);
ALTER TABLE careers ADD INDEX(employee_id);
ALTER TABLE careers ADD INDEX(city_id);
ALTER TABLE application ADD INDEX(id);
ALTER TABLE application ADD INDEX(collegemaster_id);
ALTER TABLE socialmanagements ADD INDEX(id);
ALTER TABLE socialmanagements ADD INDEX(isActive);
ALTER TABLE socialmanagements ADD INDEX(employee_id);
ALTER TABLE bookmarktypeinfos ADD INDEX(id);
ALTER TABLE bookmarktypeinfos ADD INDEX(employee_id);
ALTER TABLE bookmarks ADD INDEX(bookmarktypeinfo_id);
ALTER TABLE applicationstatusmessages ADD INDEX(id);
ALTER TABLE applicationstatusmessages ADD INDEX(application_id);
ALTER TABLE applicationstatusmessages ADD INDEX(student_id);
ALTER TABLE applicationstatusmessages ADD INDEX(college_id);
ALTER TABLE applicationstatusmessages ADD INDEX(admin_id);
ALTER TABLE applicationstatusmessages ADD INDEX(employee_id);
ALTER TABLE testimonials ADD INDEX(id);
ALTER TABLE testimonials ADD INDEX(employee_id);
ALTER TABLE application ADD INDEX(id);
ALTER TABLE application ADD INDEX(paymentstatus_id);
ALTER TABLE application ADD INDEX(applicationID);
ALTER TABLE usergroups ADD INDEX(id);
ALTER TABLE usergroups ADD INDEX(allTableInformation_id);
ALTER TABLE usergroups ADD INDEX(users_id);
ALTER TABLE usergroups ADD INDEX(employee_id);
ALTER TABLE collegelog ADD INDEX(id);
ALTER TABLE collegelog ADD INDEX(college_id);
ALTER TABLE collegelog ADD INDEX(student_id);
ALTER TABLE collegelog ADD INDEX(users_id);
ALTER TABLE collegelog ADD INDEX(userrole_id);
ALTER TABLE collegelog ADD INDEX(employee_id);
ALTER TABLE collegelog ADD INDEX(course_id);
ALTER TABLE engineeringexams ADD INDEX(id);
ALTER TABLE engineeringexams ADD INDEX(applicationId);
ALTER TABLE examtransaction ADD INDEX(id);
ALTER TABLE examtransaction ADD INDEX(employee_id);
ALTER TABLE examtransaction ADD INDEX(paymentstatus_id);
ALTER TABLE examtransaction ADD INDEX(cardtype_id);
ALTER TABLE examtransaction ADD INDEX(engineeringexams_id);
ALTER TABLE ads_managements ADD INDEX(id);
ALTER TABLE ads_managements ADD INDEX(isactive);
ALTER TABLE ads_managements ADD INDEX(users_id);
ALTER TABLE what_we_offers ADD INDEX(id);
ALTER TABLE what_we_offers ADD INDEX(status);
ALTER TABLE what_we_offers ADD INDEX(employee_id);
ALTER TABLE seo_contents ADD INDEX(id);
ALTER TABLE seo_contents ADD INDEX(pageId);
ALTER TABLE seo_contents ADD INDEX(userId);
ALTER TABLE seo_contents ADD INDEX(collegeId);
ALTER TABLE seo_contents ADD INDEX(examId);
ALTER TABLE seo_contents ADD INDEX(boardId);
ALTER TABLE seo_contents ADD INDEX(careerReleventId);
ALTER TABLE seo_contents ADD INDEX(popularCareerId);
ALTER TABLE seo_contents ADD INDEX(courseId);
ALTER TABLE seo_contents ADD INDEX(blogId);
ALTER TABLE seo_contents ADD INDEX(examSectionId);
ALTER TABLE seo_contents ADD INDEX(employee_id);
ALTER TABLE examination_types ADD INDEX(id);
ALTER TABLE examination_types ADD INDEX(status);
ALTER TABLE examination_types ADD INDEX(employee_id);
ALTER TABLE application_and_exam_statuses ADD INDEX(id);
ALTER TABLE application_and_exam_statuses ADD INDEX(status);
ALTER TABLE application_and_exam_statuses ADD INDEX(employee_id);
ALTER TABLE application_modes ADD INDEX(id);
ALTER TABLE application_modes ADD INDEX(slug);
ALTER TABLE application_modes ADD INDEX(status);
ALTER TABLE application_modes ADD INDEX(employee_id);
ALTER TABLE examination_modes ADD INDEX(id);
ALTER TABLE examination_modes ADD INDEX(slug);
ALTER TABLE examination_modes ADD INDEX(status);
ALTER TABLE examination_modes ADD INDEX(employee_id);
ALTER TABLE examination_details ADD INDEX(id);
ALTER TABLE examination_details ADD INDEX(functionalarea_id);
ALTER TABLE examination_details ADD INDEX(courses_id);
ALTER TABLE examination_details ADD INDEX(slug);
ALTER TABLE examination_details ADD INDEX(userId);
ALTER TABLE examination_details ADD INDEX(status);
ALTER TABLE examination_details ADD INDEX(totalLikes);
ALTER TABLE examination_details ADD INDEX(totalViews);
ALTER TABLE examination_details ADD INDEX(totalApplicationClick);
ALTER TABLE examination_details ADD INDEX(employee_id);
ALTER TABLE examination_details ADD INDEX(typeOfExaminations_id);
ALTER TABLE examination_important_links ADD INDEX(id);
ALTER TABLE examination_important_links ADD INDEX(examinationDetailsId);
ALTER TABLE examination_important_links ADD INDEX(employee_id);
ALTER TABLE examination_important_links ADD INDEX(typeOfExaminations_id);
ALTER TABLE eligibility_criterias ADD INDEX(id);
ALTER TABLE eligibility_criterias ADD INDEX(status);
ALTER TABLE eligibility_criterias ADD INDEX(slug);
ALTER TABLE eligibility_criterias ADD INDEX(employee_id);
ALTER TABLE exam_sections ADD INDEX(id);
ALTER TABLE exam_sections ADD INDEX(status);
ALTER TABLE exam_sections ADD INDEX(slug);
ALTER TABLE exam_sections ADD INDEX(employee_id);
ALTER TABLE exam_sections ADD INDEX(functionalarea_id);
ALTER TABLE type_of_examinations ADD INDEX(id);
ALTER TABLE type_of_examinations ADD INDEX(status);
ALTER TABLE type_of_examinations ADD INDEX(slug);
ALTER TABLE type_of_examinations ADD INDEX(university_id);
ALTER TABLE type_of_examinations ADD INDEX(examsection_id);
ALTER TABLE type_of_examinations ADD INDEX(functionalarea_id);
ALTER TABLE type_of_examinations ADD INDEX(employee_id);
ALTER TABLE exam_list_multiple_degrees ADD INDEX(id);
ALTER TABLE exam_list_multiple_degrees ADD INDEX(degree_id);
ALTER TABLE exam_list_multiple_degrees ADD INDEX(typeOfExaminations_id);
ALTER TABLE exam_list_multiple_degrees ADD INDEX(examsection_id);
ALTER TABLE exam_list_multiple_degrees ADD INDEX(functionalarea_id);
ALTER TABLE exam_list_multiple_degrees ADD INDEX(degreeSlug);
ALTER TABLE exam_application_processes ADD INDEX(id);
ALTER TABLE exam_application_processes ADD INDEX(modeofapplication);
ALTER TABLE exam_application_processes ADD INDEX(modeofpayment);
ALTER TABLE exam_application_processes ADD INDEX(typeOfExaminations_id);
ALTER TABLE exam_application_processes ADD INDEX(employee_id);
ALTER TABLE exam_application_fees ADD INDEX(id);
ALTER TABLE exam_application_fees ADD INDEX(mode);
ALTER TABLE exam_application_fees ADD INDEX(gender);
ALTER TABLE exam_application_fees ADD INDEX(typeOfExaminations_id);
ALTER TABLE exam_application_fees ADD INDEX(employee_id);
ALTER TABLE exam_eligibilities ADD INDEX(id);
ALTER TABLE exam_eligibilities ADD INDEX(degreeId);
ALTER TABLE exam_eligibilities ADD INDEX(typeOfExaminations_id);
ALTER TABLE exam_eligibilities ADD INDEX(employee_id);
ALTER TABLE exam_dates ADD INDEX(id);
ALTER TABLE exam_dates ADD INDEX(degreeId);
ALTER TABLE exam_dates ADD INDEX(eventStatus);
ALTER TABLE exam_dates ADD INDEX(typeOfExaminations_id);
ALTER TABLE exam_dates ADD INDEX(employee_id);
ALTER TABLE exam_syllabus_papers ADD INDEX(id);
ALTER TABLE exam_syllabus_papers ADD INDEX(degreeId);
ALTER TABLE exam_syllabus_papers ADD INDEX(typeOfExaminations_id);
ALTER TABLE exam_syllabus_papers ADD INDEX(employee_id);
ALTER TABLE exam_syllabus_paper_marks ADD INDEX(id);
ALTER TABLE exam_syllabus_paper_marks ADD INDEX(degreeId);
ALTER TABLE exam_syllabus_paper_marks ADD INDEX(examSyllabusPaperId);
ALTER TABLE exam_syllabus_paper_marks ADD INDEX(typeOfExaminations_id);
ALTER TABLE exam_syllabus_paper_marks ADD INDEX(employee_id);
ALTER TABLE exam_patterns ADD INDEX(id);
ALTER TABLE exam_patterns ADD INDEX(degreeId);
ALTER TABLE exam_patterns ADD INDEX(typeOfExaminations_id);
ALTER TABLE exam_patterns ADD INDEX(employee_id);
ALTER TABLE exam_admit_cards ADD INDEX(id);
ALTER TABLE exam_admit_cards ADD INDEX(degreeId);
ALTER TABLE exam_admit_cards ADD INDEX(typeOfExaminations_id);
ALTER TABLE exam_admit_cards ADD INDEX(employee_id);
ALTER TABLE exam_results ADD INDEX(id);
ALTER TABLE exam_results ADD INDEX(degreeId);
ALTER TABLE exam_results ADD INDEX(typeOfExaminations_id);
ALTER TABLE exam_results ADD INDEX(employee_id);
ALTER TABLE exam_cut_offs ADD INDEX(id);
ALTER TABLE exam_cut_offs ADD INDEX(degreeId);
ALTER TABLE exam_cut_offs ADD INDEX(typeOfExaminations_id);
ALTER TABLE exam_cut_offs ADD INDEX(employee_id);
ALTER TABLE exam_counsellings ADD INDEX(id);
ALTER TABLE exam_counsellings ADD INDEX(degreeId);
ALTER TABLE exam_counsellings ADD INDEX(modeofcounselling);
ALTER TABLE exam_counsellings ADD INDEX(typeOfExaminations_id);
ALTER TABLE exam_counsellings ADD INDEX(employee_id);
ALTER TABLE exam_counselling_dates ADD INDEX(id);
ALTER TABLE exam_counselling_dates ADD INDEX(degreeId);
ALTER TABLE exam_counselling_dates ADD INDEX(modeofcounselling);
ALTER TABLE exam_counselling_dates ADD INDEX(examCounsellingId);
ALTER TABLE exam_counselling_dates ADD INDEX(typeOfExaminations_id);
ALTER TABLE exam_counselling_dates ADD INDEX(employee_id);
ALTER TABLE exam_counselling_contacts ADD INDEX(id);
ALTER TABLE exam_counselling_contacts ADD INDEX(degreeId);
ALTER TABLE exam_counselling_contacts ADD INDEX(examCounsellingId);
ALTER TABLE exam_counselling_contacts ADD INDEX(typeOfExaminations_id);
ALTER TABLE exam_counselling_contacts ADD INDEX(employee_id);
ALTER TABLE exam_prepration_tips ADD INDEX(id);
ALTER TABLE exam_prepration_tips ADD INDEX(degreeId);
ALTER TABLE exam_prepration_tips ADD INDEX(typeOfExaminations_id);
ALTER TABLE exam_prepration_tips ADD INDEX(employee_id);
ALTER TABLE exam_questions ADD INDEX(id);
ALTER TABLE exam_questions ADD INDEX(userId);
ALTER TABLE exam_questions ADD INDEX(typeOfExaminations_id);
ALTER TABLE exam_questions ADD INDEX(employee_id);
ALTER TABLE exam_question_answers ADD INDEX(id);
ALTER TABLE exam_question_answers ADD INDEX(questionId);
ALTER TABLE exam_question_answers ADD INDEX(userId);
ALTER TABLE exam_question_answers ADD INDEX(typeOfExaminations_id);
ALTER TABLE exam_question_answers ADD INDEX(employee_id);
ALTER TABLE exam_question_answer_comments ADD INDEX(id);
ALTER TABLE exam_question_answer_comments ADD INDEX(answerId);
ALTER TABLE exam_question_answer_comments ADD INDEX(questionId);
ALTER TABLE exam_question_answer_comments ADD INDEX(userId);
ALTER TABLE exam_question_answer_comments ADD INDEX(typeOfExaminations_id);
ALTER TABLE exam_question_answer_comments ADD INDEX(employee_id);
ALTER TABLE exam_answer_key_events ADD INDEX(id);
ALTER TABLE exam_answer_key_events ADD INDEX(degreeId);
ALTER TABLE exam_answer_key_events ADD INDEX(examAnswerKeyID);
ALTER TABLE exam_answer_key_events ADD INDEX(typeOfExaminations_id);
ALTER TABLE exam_answer_key_events ADD INDEX(employee_id);
ALTER TABLE exam_answer_keys ADD INDEX(id);
ALTER TABLE exam_answer_keys ADD INDEX(degreeId);
ALTER TABLE exam_answer_keys ADD INDEX(typeOfExaminations_id);
ALTER TABLE exam_answer_keys ADD INDEX(employee_id);
ALTER TABLE exam_analysis_records ADD INDEX(id);
ALTER TABLE exam_analysis_records ADD INDEX(degreeId);
ALTER TABLE exam_analysis_records ADD INDEX(typeOfExaminations_id);
ALTER TABLE exam_analysis_records ADD INDEX(employee_id);
ALTER TABLE exam_faqs ADD INDEX(id);
ALTER TABLE exam_faqs ADD INDEX(typeOfExaminations_id);
ALTER TABLE exam_faqs ADD INDEX(employee_id);
ALTER TABLE exam_application_processes ADD INDEX(examinationtype);
ALTER TABLE exam_application_processes ADD INDEX(applicationandexamstatus);
ALTER TABLE exam_application_processes ADD INDEX(examinationmode);
ALTER TABLE exam_application_processes ADD INDEX(eligibilitycriteria);
ALTER TABLE counseling_boards ADD INDEX(id);
ALTER TABLE counseling_boards ADD INDEX(status);
ALTER TABLE counseling_boards ADD INDEX(employee_id);
ALTER TABLE counseling_board_details ADD INDEX(id);
ALTER TABLE counseling_board_details ADD INDEX(counselingBoardId);
ALTER TABLE counseling_board_details ADD INDEX(employee_id);
ALTER TABLE counseling_board_imp_dates ADD INDEX(id);
ALTER TABLE counseling_board_imp_dates ADD INDEX(counselingBoardId);
ALTER TABLE counseling_board_imp_dates ADD INDEX(employee_id);
ALTER TABLE counseling_board_latest_updates ADD INDEX(id);
ALTER TABLE counseling_board_latest_updates ADD INDEX(counselingBoardId);
ALTER TABLE counseling_board_latest_updates ADD INDEX(employee_id);
ALTER TABLE counseling_board_highlights ADD INDEX(id);
ALTER TABLE counseling_board_highlights ADD INDEX(counselingBoardId);
ALTER TABLE counseling_board_highlights ADD INDEX(employee_id);
ALTER TABLE counseling_board_exam_dates ADD INDEX(id);
ALTER TABLE counseling_board_exam_dates ADD INDEX(counselingBoardId);
ALTER TABLE counseling_board_exam_dates ADD INDEX(employee_id);
ALTER TABLE counseling_board_sample_papers ADD INDEX(id);
ALTER TABLE counseling_board_sample_papers ADD INDEX(counselingBoardId);
ALTER TABLE counseling_board_sample_papers ADD INDEX(employee_id);
ALTER TABLE counseling_board_syllabus ADD INDEX(id);
ALTER TABLE counseling_board_syllabus ADD INDEX(counselingBoardId);
ALTER TABLE counseling_board_syllabus ADD INDEX(employee_id);
ALTER TABLE counseling_board_admission_dates ADD INDEX(id);
ALTER TABLE counseling_board_admission_dates ADD INDEX(counselingBoardId);
ALTER TABLE counseling_board_admission_dates ADD INDEX(employee_id);
ALTER TABLE counseling_career_interests ADD INDEX(id);
ALTER TABLE counseling_career_interests ADD INDEX(status);
ALTER TABLE counseling_career_interests ADD INDEX(functionalarea_id);
ALTER TABLE counseling_career_interests ADD INDEX(employee_id);
ALTER TABLE counseling_career_relevants ADD INDEX(id);
ALTER TABLE counseling_career_relevants ADD INDEX(careerInterest);
ALTER TABLE counseling_career_relevants ADD INDEX(functionalarea_id);
ALTER TABLE counseling_career_relevants ADD INDEX(employee_id);
ALTER TABLE counseling_career_details ADD INDEX(id);
ALTER TABLE counseling_career_details ADD INDEX(functionalarea_id);
ALTER TABLE counseling_career_details ADD INDEX(careerRelevantId);
ALTER TABLE counseling_career_details ADD INDEX(employee_id);
ALTER TABLE counseling_career_skill_requirements ADD INDEX(id);
ALTER TABLE counseling_career_skill_requirements ADD INDEX(careerDetailsId);
ALTER TABLE counseling_career_skill_requirements ADD INDEX(employee_id);
ALTER TABLE counseling_career_where_to_studies ADD INDEX(id);
ALTER TABLE counseling_career_where_to_studies ADD INDEX(careerDetailsId);
ALTER TABLE counseling_career_where_to_studies ADD INDEX(employee_id);
ALTER TABLE counseling_career_job_role_saleries ADD INDEX(id);
ALTER TABLE counseling_career_job_role_saleries ADD INDEX(careerDetailsId);
ALTER TABLE counseling_career_job_role_saleries ADD INDEX(employee_id);
ALTER TABLE counseling_courses_job_careers ADD INDEX(id);
ALTER TABLE counseling_courses_job_careers ADD INDEX(coursesDetailsId);
ALTER TABLE counseling_courses_job_careers ADD INDEX(employee_id);
ALTER TABLE counseling_courses_more_titles ADD INDEX(id);
ALTER TABLE counseling_courses_more_titles ADD INDEX(coursesDetailsId);
ALTER TABLE counseling_courses_more_titles ADD INDEX(employee_id);
ALTER TABLE counseling_courses_more_details ADD INDEX(id);
ALTER TABLE counseling_courses_more_details ADD INDEX(coursesDetailsId);
ALTER TABLE counseling_courses_more_details ADD INDEX(functionalarea_id);
ALTER TABLE counseling_courses_more_details ADD INDEX(degree_id);
ALTER TABLE counseling_courses_more_details ADD INDEX(employee_id);
ALTER TABLE counseling_courses_details ADD INDEX(id);
ALTER TABLE counseling_courses_details ADD INDEX(educationlevel_id);
ALTER TABLE counseling_courses_details ADD INDEX(functionalarea_id);
ALTER TABLE counseling_courses_details ADD INDEX(employee_id);
ALTER TABLE counseling_courses_education_levels ADD INDEX(id);
ALTER TABLE counseling_courses_education_levels ADD INDEX(educationlevel_id);
ALTER TABLE counseling_courses_education_levels ADD INDEX(functionalarea_id);
ALTER TABLE counseling_courses_education_levels ADD INDEX(coursesDetailsId);
ALTER TABLE counseling_courses_education_levels ADD INDEX(employee_id);
ALTER TABLE faculty ADD INDEX(id);
ALTER TABLE faculty ADD INDEX(gender);
ALTER TABLE faculty ADD INDEX(country_id);
ALTER TABLE faculty ADD INDEX(state_id);
ALTER TABLE faculty ADD INDEX(city_id);
ALTER TABLE faculty ADD INDEX(designation);
ALTER TABLE contentcategory ADD INDEX(id);
ALTER TABLE contentcategory ADD INDEX(status);
ALTER TABLE contents ADD INDEX(id);
ALTER TABLE contents ADD INDEX(status);
ALTER TABLE contents ADD INDEX(contentcategory_id);
ALTER TABLE slider_managers ADD INDEX(id);
ALTER TABLE slider_managers ADD INDEX(status);
ALTER TABLE slider_managers ADD INDEX(isShowCollegeCount);
ALTER TABLE slider_managers ADD INDEX(isShowExamCount);
ALTER TABLE slider_managers ADD INDEX(isShowCourseCount);
ALTER TABLE slider_managers ADD INDEX(isShowBlogCount);
ALTER TABLE slider_managers ADD INDEX(employee_id);
ALTER TABLE latest_updates ADD INDEX(id);
ALTER TABLE latest_updates ADD INDEX(status);
ALTER TABLE latest_updates ADD INDEX(users_id);
ALTER TABLE latest_updates ADD INDEX(employee_id);
ALTER TABLE seo_contents ADD INDEX(educationLevelId);
ALTER TABLE seo_contents ADD INDEX(degreeId);
ALTER TABLE seo_contents ADD INDEX(functionalAreaId);
ALTER TABLE seo_contents ADD INDEX(topCourseId);
ALTER TABLE seo_contents ADD INDEX(universityId);
ALTER TABLE seo_contents ADD INDEX(countryId);
ALTER TABLE seo_contents ADD INDEX(stateId);
ALTER TABLE seo_contents ADD INDEX(cityId);
ALTER TABLE seo_contents ADD INDEX(newsId);
ALTER TABLE seo_contents ADD INDEX(newsTagId);
ALTER TABLE seo_contents ADD INDEX(newsTypeId);
ALTER TABLE seo_contents ADD INDEX(askQuestionId);
ALTER TABLE seo_contents ADD INDEX(askTagId);
ALTER TABLE country ADD INDEX(isShowOnTop);
ALTER TABLE country ADD INDEX(isShowOnHome);
ALTER TABLE country ADD INDEX(totalCollegeRegAddress);
ALTER TABLE country ADD INDEX(totalCollegeByCampusAddress);
ALTER TABLE course ADD INDEX(isShowOnTop);
ALTER TABLE course ADD INDEX(isShowOnHome);
ALTER TABLE degree ADD INDEX(isShowOnTop);
ALTER TABLE degree ADD INDEX(isShowOnHome);
ALTER TABLE functionalarea ADD INDEX(isShowOnTop);
ALTER TABLE functionalarea ADD INDEX(isShowOnHome);
ALTER TABLE university ADD INDEX(isShowOnTop);
ALTER TABLE university ADD INDEX(isShowOnHome);
ALTER TABLE educationlevel ADD INDEX(isShowOnTop);
ALTER TABLE educationlevel ADD INDEX(isShowOnHome);
ALTER TABLE state ADD INDEX(isShowOnTop);
ALTER TABLE state ADD INDEX(isShowOnHome);
ALTER TABLE state ADD INDEX(totalCollegeRegAddress);
ALTER TABLE state ADD INDEX(totalCollegeByCampusAddress);
ALTER TABLE city ADD INDEX(isShowOnTop);
ALTER TABLE city ADD INDEX(isShowOnHome);
ALTER TABLE city ADD INDEX(totalCollegeRegAddress);
ALTER TABLE city ADD INDEX(totalCollegeByCampusAddress);
ALTER TABLE collegeprofile ADD INDEX(isShowOnTop);
ALTER TABLE collegeprofile ADD INDEX(isShowOnHome);
ALTER TABLE collegeprofile ADD INDEX(registeredAddressCityId);
ALTER TABLE collegeprofile ADD INDEX(registeredAddressStateId);
ALTER TABLE collegeprofile ADD INDEX(registeredAddressCountryId);
ALTER TABLE collegeprofile ADD INDEX(campusAddressCityId);
ALTER TABLE collegeprofile ADD INDEX(campusAddressStateId);
ALTER TABLE collegeprofile ADD INDEX(campusAddressCountryId);
ALTER TABLE news ADD INDEX(id);
ALTER TABLE news ADD INDEX(isactive);
ALTER TABLE news ADD INDEX(users_id);
ALTER TABLE news ADD INDEX(slug);
ALTER TABLE news_tags ADD INDEX(id);
ALTER TABLE news_tags ADD INDEX(slug);
ALTER TABLE news_types ADD INDEX(id);
ALTER TABLE news_types ADD INDEX(slug);
ALTER TABLE ask_questions ADD INDEX(id);
ALTER TABLE ask_questions ADD INDEX(userId);
ALTER TABLE ask_questions ADD INDEX(status);
ALTER TABLE ask_questions ADD INDEX(employee_id);
ALTER TABLE ask_questions ADD INDEX(totalAnswerCount);
ALTER TABLE ask_questions ADD INDEX(totalCommentsCount);
ALTER TABLE ask_question_answers ADD INDEX(id);
ALTER TABLE ask_question_answers ADD INDEX(questionId);
ALTER TABLE ask_question_answers ADD INDEX(userId);
ALTER TABLE ask_question_answers ADD INDEX(employee_id);
ALTER TABLE ask_question_answers ADD INDEX(status);
ALTER TABLE ask_question_answer_comments ADD INDEX(id);
ALTER TABLE ask_question_answer_comments ADD INDEX(answerId);
ALTER TABLE ask_question_answer_comments ADD INDEX(questionId);
ALTER TABLE ask_question_answer_comments ADD INDEX(userId);
ALTER TABLE ask_question_answer_comments ADD INDEX(employee_id);
ALTER TABLE ask_question_answer_comments ADD INDEX(status);
ALTER TABLE ask_question_tags ADD INDEX(id);
ALTER TABLE ask_question_tags ADD INDEX(slug);
ALTER TABLE college_management_details ADD INDEX(id);
ALTER TABLE college_management_details ADD INDEX(users_id);
ALTER TABLE college_management_details ADD INDEX(collegeprofile_id);
ALTER TABLE college_management_details ADD INDEX(employee_id);
ALTER TABLE college_scholarships ADD INDEX(id);
ALTER TABLE college_scholarships ADD INDEX(users_id);
ALTER TABLE college_scholarships ADD INDEX(collegeprofile_id);
ALTER TABLE college_scholarships ADD INDEX(employee_id);
ALTER TABLE college_social_media_links ADD INDEX(id);
ALTER TABLE college_social_media_links ADD INDEX(isActive);
ALTER TABLE college_social_media_links ADD INDEX(users_id);
ALTER TABLE college_social_media_links ADD INDEX(collegeprofile_id);
ALTER TABLE college_social_media_links ADD INDEX(employee_id);
ALTER TABLE college_cut_offs ADD INDEX(id);
ALTER TABLE college_cut_offs ADD INDEX(educationlevel_id);
ALTER TABLE college_cut_offs ADD INDEX(functionalarea_id);
ALTER TABLE college_cut_offs ADD INDEX(degree_id);
ALTER TABLE college_cut_offs ADD INDEX(coursetype_id);
ALTER TABLE college_cut_offs ADD INDEX(course_id);
ALTER TABLE college_cut_offs ADD INDEX(users_id);
ALTER TABLE college_cut_offs ADD INDEX(collegeprofile_id);
ALTER TABLE college_cut_offs ADD INDEX(employee_id);
ALTER TABLE college_reviews ADD INDEX(id);
ALTER TABLE college_reviews ADD INDEX(guestUserId);
ALTER TABLE college_reviews ADD INDEX(users_id);
ALTER TABLE college_reviews ADD INDEX(collegeprofile_id);
ALTER TABLE college_reviews ADD INDEX(employee_id);
ALTER TABLE faculty_experiences ADD INDEX(id);
ALTER TABLE faculty_experiences ADD INDEX(faculty_id);
ALTER TABLE faculty_experiences ADD INDEX(users_id);
ALTER TABLE faculty_experiences ADD INDEX(collegeprofile_id);
ALTER TABLE faculty_experiences ADD INDEX(employee_id);
ALTER TABLE faculty_qualifications ADD INDEX(id);
ALTER TABLE faculty_qualifications ADD INDEX(faculty_id);
ALTER TABLE faculty_qualifications ADD INDEX(users_id);
ALTER TABLE faculty_qualifications ADD INDEX(collegeprofile_id);
ALTER TABLE faculty_qualifications ADD INDEX(employee_id);
ALTER TABLE college_faqs ADD INDEX(id);
ALTER TABLE college_faqs ADD INDEX(users_id);
ALTER TABLE college_faqs ADD INDEX(collegeprofile_id);
ALTER TABLE college_faqs ADD INDEX(employee_id);
ALTER TABLE college_sports_activities ADD INDEX(id);
ALTER TABLE college_sports_activities ADD INDEX(typeOfActivity);
ALTER TABLE college_sports_activities ADD INDEX(users_id);
ALTER TABLE college_sports_activities ADD INDEX(collegeprofile_id);
ALTER TABLE college_sports_activities ADD INDEX(employee_id);
ALTER TABLE college_master_associate_faculties ADD INDEX(id);
ALTER TABLE college_master_associate_faculties ADD INDEX(faculty_id);
ALTER TABLE college_master_associate_faculties ADD INDEX(collegemaster_id);
ALTER TABLE college_master_associate_faculties ADD INDEX(functionalarea_id);
ALTER TABLE college_master_associate_faculties ADD INDEX(educationlevel_id);
ALTER TABLE college_master_associate_faculties ADD INDEX(degree_id);
ALTER TABLE college_master_associate_faculties ADD INDEX(coursetype_id);
ALTER TABLE college_master_associate_faculties ADD INDEX(course_id);
ALTER TABLE college_master_associate_faculties ADD INDEX(users_id);
ALTER TABLE college_master_associate_faculties ADD INDEX(collegeprofile_id);
ALTER TABLE college_master_associate_faculties ADD INDEX(employee_id);
ALTER TABLE faculty_departments ADD INDEX(id);
ALTER TABLE faculty_departments ADD INDEX(collegemaster_id);
ALTER TABLE faculty_departments ADD INDEX(functionalarea_id);
ALTER TABLE faculty_departments ADD INDEX(educationlevel_id);
ALTER TABLE faculty_departments ADD INDEX(degree_id);
ALTER TABLE faculty_departments ADD INDEX(coursetype_id);
ALTER TABLE faculty_departments ADD INDEX(course_id);
ALTER TABLE faculty_departments ADD INDEX(faculty_id);
ALTER TABLE faculty_departments ADD INDEX(users_id);
ALTER TABLE faculty_departments ADD INDEX(collegeprofile_id);
ALTER TABLE faculty_departments ADD INDEX(employee_id);
ALTER TABLE college_admission_procedures ADD INDEX(id);
ALTER TABLE college_admission_procedures ADD INDEX(functionalarea_id);
ALTER TABLE college_admission_procedures ADD INDEX(educationlevel_id);
ALTER TABLE college_admission_procedures ADD INDEX(degree_id);
ALTER TABLE college_admission_procedures ADD INDEX(coursetype_id);
ALTER TABLE college_admission_procedures ADD INDEX(course_id);
ALTER TABLE college_admission_procedures ADD INDEX(users_id);
ALTER TABLE college_admission_procedures ADD INDEX(collegeprofile_id);
ALTER TABLE college_admission_procedures ADD INDEX(employee_id);
ALTER TABLE college_admission_important_dateds ADD INDEX(id);
ALTER TABLE college_admission_important_dateds ADD INDEX(collegeAdmissionProcedure_id);
ALTER TABLE college_admission_important_dateds ADD INDEX(users_id);
ALTER TABLE college_admission_important_dateds ADD INDEX(collegeprofile_id);
ALTER TABLE college_admission_important_dateds ADD INDEX(employee_id);
ALTER TABLE exam_counselling_forms ADD INDEX(id);
ALTER TABLE exam_counselling_forms ADD INDEX(city_id);
ALTER TABLE exam_counselling_forms ADD INDEX(course_id);
ALTER TABLE exam_counselling_forms ADD INDEX(exam_id);
ALTER TABLE exam_counselling_forms ADD INDEX(users_id);
ALTER TABLE exam_counselling_forms ADD INDEX(employee_id);
ALTER TABLE collegeprofile ADD INDEX(slug);
ALTER TABLE studentprofile ADD INDEX(slug);
ALTER TABLE landing_page_query_forms ADD INDEX(id);
ALTER TABLE landing_page_query_forms ADD INDEX(users_id);
ALTER TABLE landing_page_query_forms ADD INDEX(employee_id);
<!-- ALTER TABLE country ADD INDEX(pageslug);
ALTER TABLE course ADD INDEX(pageslug);
ALTER TABLE degree ADD INDEX(pageslug);
ALTER TABLE functionalarea ADD INDEX(pageslug);
ALTER TABLE university ADD INDEX(pageslug);
ALTER TABLE educationlevel ADD INDEX(pageslug);
ALTER TABLE state ADD INDEX(pageslug);
ALTER TABLE city ADD INDEX(pageslug); -->