<?php echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"; ?>
<?php echo "<?xml-stylesheet type=\"text/xsl\" href=\"/new-assets/css/main-sitemap.xsl\"?>"; ?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    <sitemap>
		<loc>{{ env('APP_URL').'/sitemap/website.xml' }}</loc>
		<lastmod>{{$lastmodDate}}</lastmod>
	</sitemap>
	<sitemap>
		<loc>{{ env('APP_URL').'/sitemap/study-abroad.xml' }}</loc>
		<lastmod>{{$lastmodDate}}</lastmod>
	</sitemap>
	@if($universityPageCount > 0)
        @for( $counts = 0; $counts <= $universityPageCount; $counts++)
            @if( $counts > 0)
                <sitemap>
					<loc>{{ env('APP_URL').'/sitemap/university/list-'.$counts.'.xml' }}</loc>
					<lastmod>{{$lastmodDate}}</lastmod>
				</sitemap>
            @endif
        @endfor
    @endif
	<sitemap>
		<loc>{{ env('APP_URL').'/sitemap/education-level-college-list.xml' }}</loc>
		<lastmod>{{$lastmodDate}}</lastmod>
	</sitemap>
	<sitemap>
		<loc>{{ env('APP_URL').'/sitemap/stream-college-list.xml' }}</loc>
		<lastmod>{{$lastmodDate}}</lastmod>
	</sitemap>
	<sitemap>
		<loc>{{ env('APP_URL').'/sitemap/degree-college-list.xml' }}</loc>
		<lastmod>{{$lastmodDate}}</lastmod>
	</sitemap>
	<sitemap>
		<loc>{{ env('APP_URL').'/sitemap/course-college-list.xml' }}</loc>
		<lastmod>{{$lastmodDate}}</lastmod>
	</sitemap>
	<sitemap>
		<loc>{{ env('APP_URL').'/sitemap/stream-list.xml' }}</loc>
		<lastmod>{{$lastmodDate}}</lastmod>
	</sitemap>
	<sitemap>
		<loc>{{ env('APP_URL').'/sitemap/degree-list.xml' }}</loc>
		<lastmod>{{$lastmodDate}}</lastmod>
	</sitemap>
	<sitemap>
		<loc>{{ env('APP_URL').'/sitemap/examination.xml' }}</loc>
		<lastmod>{{$lastmodDate}}</lastmod>
	</sitemap>
	<sitemap>
		<loc>{{ env('APP_URL').'/sitemap/careers-opportunities.xml' }}</loc>
		<lastmod>{{$lastmodDate}}</lastmod>
	</sitemap>
	<sitemap>
		<loc>{{ env('APP_URL').'/sitemap/popular-careers.xml' }}</loc>
		<lastmod>{{$lastmodDate}}</lastmod>
	</sitemap>
	<sitemap>
		<loc>{{ env('APP_URL').'/sitemap/careers-courses.xml' }}</loc>
		<lastmod>{{$lastmodDate}}</lastmod>
	</sitemap>
	<sitemap>
		<loc>{{ env('APP_URL').'/sitemap/boards.xml' }}</loc>
		<lastmod>{{$lastmodDate}}</lastmod>
	</sitemap>
	<sitemap>
		<loc>{{ env('APP_URL').'/sitemap/blog.xml' }}</loc>
		<lastmod>{{$lastmodDate}}</lastmod>
	</sitemap>
	<sitemap>
		<loc>{{ env('APP_URL').'/sitemap/news.xml' }}</loc>
		<lastmod>{{$lastmodDate}}</lastmod>
	</sitemap>
    @if($collegePageCount > 0)
        @for( $counts = 0; $counts <= $collegePageCount; $counts++)
            @if( $counts > 0)
                <sitemap>
					<loc>{{ env('APP_URL').'/sitemap/college/list-'.$counts.'.xml' }}</loc>
					<lastmod>{{$lastmodDate}}</lastmod>
				</sitemap>
            @endif
        @endfor
    @endif
    <sitemap>
		<loc>{{ env('APP_URL').'/sitemap/ask-tags.xml' }}</loc>
		<lastmod>{{$lastmodDate}}</lastmod>
	</sitemap>
    @if($askPageCount > 0)
        @for( $counts = 0; $counts <= $askPageCount; $counts++)
            @if( $counts > 0)
                <sitemap>
					<loc>{{ env('APP_URL').'/sitemap/ask/list-'.$counts.'.xml' }}</loc>
					<lastmod>{{$lastmodDate}}</lastmod>
				</sitemap>
            @endif
        @endfor
    @endif
    @if($reviewPageCount > 0)
        @for( $counts = 0; $counts <= $reviewPageCount; $counts++)
            @if( $counts > 0)
                <sitemap>
					<loc>{{ env('APP_URL').'/sitemap/reviews/list-'.$counts.'.xml' }}</loc>
					<lastmod>{{$lastmodDate}}</lastmod>
				</sitemap>
            @endif
        @endfor
    @endif
    @if($statePageCount > 0)
        @for( $counts = 0; $counts <= $statePageCount; $counts++)
            @if( $counts > 0)
                <sitemap>
					<loc>{{ env('APP_URL').'/sitemap/state-wise-college/list-'.$counts.'.xml' }}</loc>
					<lastmod>{{$lastmodDate}}</lastmod>
				</sitemap>
            @endif
        @endfor
    @endif
    @if($cityPageCount > 0)
        @for( $counts = 0; $counts <= $cityPageCount; $counts++)
            @if( $counts > 0)
                <sitemap>
					<loc>{{ env('APP_URL').'/sitemap/city-wise-college/list-'.$counts.'.xml' }}</loc>
					<lastmod>{{$lastmodDate}}</lastmod>
				</sitemap>
            @endif
        @endfor
    @endif
    <sitemap>
		<loc>{{ env('APP_URL').'/sitemap/country-wise-state.xml' }}</loc>
		<lastmod>{{$lastmodDate}}</lastmod>
	</sitemap>
    @if($statePageCount > 0)
        @for( $counts = 0; $counts <= $statePageCount; $counts++)
            @if( $counts > 0)
                <sitemap>
					<loc>{{ env('APP_URL').'/sitemap/state-wise-cities/list-'.$counts.'.xml' }}</loc>
					<lastmod>{{$lastmodDate}}</lastmod>
				</sitemap>
            @endif
        @endfor
    @endif
</sitemapindex>
<!-- XML Sitemap generated by Yoast SEO -->