@extends('website/home-layouts.master')


@section('content')

<!-- <div class="container  content-sm">
	<div class="container">
		<div class="row">
			<div class="col-md-12 md-margin-bottom-50">
				@foreach($getSitemapObj as $item)
					<input type="hidden" name="slug" value="{{ $item->contentslug }}">
					<div>
						{!! $item->description !!}
					</div>		
				@endforeach
			</div>
		</div>
	</div>
</div> -->

<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<title>admissionx.com Site Map - Generated by www.xml-sitemaps.com</title>
	<meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport" />
	<style>
	body {
		background-color: #fff;
		font-family: "Roboto", "Helvetica", "Arial", sans-serif;
		margin: 0;
	}

	#top {

		background-color: #fbb927;
		font-size: 16px;
		padding-bottom: 40px;
	}

	nav {
		font-size: 24px;

		margin: 0px 30px 0px;
		border-bottom-left-radius: 6px;
		border-bottom-right-radius: 6px;
		background-color: #f3f3f3;
		color: #666;
		box-shadow: 0 10px 20px -12px rgba(0, 0, 0, 0.42), 0 3px 20px 0px rgba(0, 0, 0, 0.12), 0 8px 10px -5px rgba(0, 0, 0, 0.2);
		padding: 10px 0;
		text-align: center;
		z-index: 1;
	}

	h1 {
		margin: auto;
		padding: 10px;
		max-width: 350px;
		color: #666;
	}

	h1 span {
		float: right;
	}

	h1 a {
		font-weight: normal;
		display: block;
	}


	#cont {
		position: relative;
		border-radius: 6px;
		box-shadow: 0 16px 24px 2px rgba(0, 0, 0, 0.14), 0 6px 30px 5px rgba(0, 0, 0, 0.12), 0 8px 10px -5px rgba(0, 0, 0, 0.2);

		background: #f3f3f3;

		margin: -20px 30px 0px 30px;
		padding: 20px;
	}

	.lpage a:link,
	a:visited {
		color: #0180AF;
		text-decoration: underline;
	}

	a:hover {
		color: #e8690c;
	}


	#footer {
		padding: 10px;
		text-align: center;
	}

	ul {
    	margin: 0px;

    	padding: 0px;
    	list-style: none;
	}
	li {
		margin: 0px;
	}
	li ul {
		margin-left: 20px;
	}

	.lhead {
		background: #ddd;
		padding: 10px;
    	margin: 10px 0px;
	}

	.lcount {
		padding: 0px 10px;
	}

	.lpage {
		border-bottom: #ddd 1px solid;
		padding: 5px;
	}
	.last-page {
		border: none;
	}
	</style>
</head>

<body>
	<div id="top">
		<nav>admissionx.com HTML Site Map</nav>
		<h1><a href="https://www.admissionx.com">admissionx.com Homepage</a></h1>
	</div>
	<div id="cont">
		<ul class="level-0">
			<li class="lpage"><a href="https://www.admissionx.com/" title="Machinery planet">Machinery planet</a></li>
			<li class="lpage"><a href="https://www.admissionx.com/news/" title="News Page | admissionx.com">News Page</a></li>
			<li class="lpage"><a href="https://www.admissionx.com/about-us/" title="About Us | admissionx.com">About Us</a></li>
			<li class="lpage"><a href="https://www.admissionx.com/contact-us/" title="Contact Us | admissionx.com">Contact Us</a></li>
			<li class="lpage"><a href="https://www.admissionx.com/exhibition-list/" title="Exhibition Calendar | admissionx.com">Exhibition Calendar</a></li>
			<li class="lpage"><a href="https://www.admissionx.com/auction-list/" title="Auction Calendar | admissionx.com">Auction Calendar</a></li>
			<li class="lpage"><a href="https://www.admissionx.com/all-category-list/" title="Category Page | admissionx.com">Category Page</a></li>
			<li class="lpage"><a href="https://www.admissionx.com/seller-register/" title="Seller Registration Page | admissionx.com">Seller Registration Page</a></li>
			<li class="lpage"><a href="https://www.admissionx.com/dealer-register/" title="Dealer Registration Page | admissionx.com">Dealer Registration Page</a></li>
			<li class="lpage"><a href="https://www.admissionx.com/trader-register/" title="Trader Registration Page | admissionx.com">Trader Registration Page</a></li>
			<li class="lpage"><a href="https://www.admissionx.com/buyer-register/" title="Buyer Registration Page | admissionx.com">Buyer Registration Page</a></li>
			<li class="lpage"><a href="https://www.admissionx.com/user-register/" title="Guest Registration Page | admissionx.com">Guest Registration Page</a></li>
			<li class="lpage"><a href="https://www.admissionx.com/privacy-policy" title="Privacy Policy | admissionx.com">Privacy Policy</a></li>
			<li class="lpage"><a href="https://www.admissionx.com/policies/" title="Policies | admissionx.com">Policies</a></li>
			<li class="lpage"><a href="https://www.admissionx.com/terms-of-use/" title="Terms of Use | admissionx.com">Terms of Use</a></li>
			<li class="lpage"><a href="https://www.admissionx.com/terms-and-conditions/" title="Terms and Conditions | admissionx.com">Terms and Conditions</a></li>
			<li class="lpage"><a href="https://www.admissionx.com/register/" title="Registration Page | admissionx.com">Registration Page</a></li>
			<li class="lpage last-page"><a href="https://www.admissionx.com/login/" title="Login Page | admissionx.com">Login Page</a></li><li>
			<li class="lpage"><a href="https://www.admissionx.com/buy-machinery/" title="Machinery planet">Buy Page</a></li>
			<li class="lpage"><a href="https://www.admissionx.com/rent-machinery/" title="Machinery planet">Rent Page</a></li>
			<li class="lpage"><a href="https://www.admissionx.com/auction-machinery/" title="Machinery planet">Auction Page</a></li>
			<li class="lpage"><a href="https://www.admissionx.com/seller-listing/" title="Find Seller Page | admissionx.com">Find Seller Page</a></li>
			<li class="lpage"><a href="https://www.admissionx.com/dealer-listing/" title="Find Dealer Page | admissionx.com">Find Dealer Page</a></li>
			<li class="lpage"><a href="https://www.admissionx.com/search/" title="Machinery planet search">Machinery planet Search Page</a></li>
			<li class="lpage"><a href="https://www.admissionx.com/search?packages=3/" title="Machinery Planet Premium Page">Machinery Planet Premium Page </a></li>
			<li class="lpage"><a href="https://www.admissionx.com/search?packages=1/" title="Machinery Planet Standard Page">Machinery Planet Standard Page</a></li>
			<li class="lpage"><a href="https://www.admissionx.com/search?packages=2/" title="Machinery Planet Featured Page">Machinery Planet Featured Page</a></li>


			<li class="lhead">Exhibition/  <span class="lcount">{{ sizeof($exhibitionList) }} pages</span></li>
            @foreach ($exhibitionList as $post)
		        <li class="lpage"><a href="https://www.admissionx.com/exhibition-details/{{ $post->exhibitionSlug }}" title="{{$post->exhibitionName}}">{{$post->exhibitionName}}</a></li>
		    @endforeach

		    <li class="lhead">Auction/  <span class="lcount">{{ sizeof($auctionList) }} pages</span></li>
            @foreach ($auctionList as $post)
		        <li class="lpage"><a href="https://www.admissionx.com/auction-details/{{ $post->auctionSlug }}" title="{{$post->auctionName}}">{{$post->auctionName}}</a></li>
		    @endforeach

			<li class="lhead">Class/  <span class="lcount">{{ sizeof($classForSale) }} pages for sale</span></li>
            @foreach ($classForSale as $post)
		        {{--*/
		            $classCount = ceil($post->classCount/21);
		        /*--}}
		        @if($classCount > 0)
		            @for( $count = 0; $count <= $classCount; $count++)
		                @if( $count == 0)
		                    <li class="lpage"><a href="https://www.admissionx.com/{{ $post->classesSlug }}-for-sale{!! ($count > 1)? '?page='.$count.'/' : '/' !!}" title="{{$post->classesName}} Equipment for Sale">{{$post->classesName}} for Sale {!! ($count > 1)? 'Page '.$count : '' !!}</a></li>
		                @endif
		            @endfor
		        @else
		            <li class="lpage"><a href="https://www.admissionx.com/{{ $post->classesSlug }}-for-sale/" title="{{$post->classesName}} for Sale or Rent">{{$post->classesName}} for Sale</a></li>
		        @endif
		    @endforeach


		    <li class="lhead">Category/  <span class="lcount">{{ sizeof($categoriesForSale) }} pages for sale</span></li>
            @foreach ($categoriesForSale as $post)
		        {{--*/
		            $categoryCount = ceil($post->categoryCount/21);
		        /*--}}
		        @if($categoryCount > 0)
		            @for( $count = 0; $count <= $categoryCount; $count++)
		                @if( $count == 0)
		                    <li class="lpage"><a href="https://www.admissionx.com/{{ $post->categoriesSlug }}-for-sale{!! ($count > 1)? '?page='.$count.'/' : '/' !!}" title="{{$post->categoriesName}} Equipment for Sale">{{$post->categoriesName}} for Sale {!! ($count > 1)? 'Page '.$count : '' !!}</a></li>
		                @endif
		            @endfor
		        @else
		            <li class="lpage"><a href="https://www.admissionx.com/{{ $post->categoriesSlug }}-for-sale/" title="{{$post->categoriesName}} for Sale or Rent">{{$post->categoriesName}} for Sale</a></li>
		        @endif
		    @endforeach



		    <li class="lhead">Child Category/  <span class="lcount">{{ sizeof($childCategoryForSale) }} pages for sale</span></li>
            @foreach ($childCategoryForSale as $post)
		        {{--*/
		            $childCategoryCount = ceil($post->childCategoryCount/21);
		        /*--}}
		        @if($childCategoryCount > 0)
		            @for( $count = 0; $count <= $childCategoryCount; $count++)
		                @if( $count == 0)
		                    <li class="lpage"><a href="https://www.admissionx.com/{{ $post->child_categoriesSlug }}-for-sale{!! ($count > 1)? '?page='.$count.'/' : '/' !!}" title="{{$post->child_categoriesName}} Equipment for Sale">{{$post->child_categoriesName}} for Sale {!! ($count > 1)? 'Page '.$count : '' !!}</a></li>
		                @endif
		            @endfor
		        @else
		            <li class="lpage"><a href="https://www.admissionx.com/{{ $post->child_categoriesSlug }}-for-sale/" title="{{$post->child_categoriesName}} for Sale or Rent">{{$post->child_categoriesName}} for Sale</a></li>
		        @endif
		    @endforeach


		   	<li class="lhead">Makes/  <span class="lcount">{{ sizeof($makesForSale) }} pages for sale</span></li>
            @foreach ($makesForSale as $post)
		        {{--*/
		            $makeCount = ceil($post->makeCount/21);
		        /*--}}
		        @if($makeCount > 0)
		            @for( $count = 0; $count <= $makeCount; $count++)
		                @if( $count == 0)
		                    <li class="lpage"><a href="https://www.admissionx.com/{{ $post->makesSlug }}-for-sale{!! ($count > 1)? '?page='.$count.'/' : '/' !!}" title="{{$post->makesName}} Equipment for Sale">{{$post->makesName}} for Sale {!! ($count > 1)? 'Page '.$count : '' !!}</a></li>
		                @endif
		            @endfor
		        @else
		            <li class="lpage"><a href="https://www.admissionx.com/{{ $post->makesSlug }}-for-sale/" title="{{$post->makesName}} for Sale or Rent">{{$post->makesName}} for Sale</a></li>
		        @endif
		    @endforeach


		    <li class="lhead">Models/  <span class="lcount">{{ sizeof($modelForSale) }} pages for sale</span></li>
            @foreach ($modelForSale as $post)
		        {{--*/
		            $modelCount = ceil($post->modelCount/21);
		        /*--}}
		        @if($modelCount > 0)
		            @for( $count = 0; $count <= $modelCount; $count++)
		                @if( $count == 0)
		                    <li class="lpage"><a href="https://www.admissionx.com/{{ $post->make_modelsSlug }}-for-sale{!! ($count > 1)? '?page='.$count.'/' : '/' !!}" title="{{$post->make_modelsName}} Equipment for Sale">{{$post->make_modelsName}} for Sale {!! ($count > 1)? 'Page '.$count : '' !!}</a></li>
		                @endif
		            @endfor
		        @else
		            <li class="lpage"><a href="https://www.admissionx.com/{{ $post->make_modelsSlug }}-for-sale/" title="{{$post->make_modelsName}} for Sale or Rent">{{$post->make_modelsName}} for Sale</a></li>
		        @endif
		    @endforeach


		    <li class="lhead">Sub Models/  <span class="lcount">{{ sizeof($subModelForSale) }} pages for sale</span></li>
            @foreach ($subModelForSale as $post)
		        {{--*/
		            $subModelCount = ceil($post->subModelCount/21);
		        /*--}}
		        @if($subModelCount > 0)
		            @for( $count = 0; $count <= $subModelCount; $count++)
		                @if( $count == 0)
		                    <li class="lpage"><a href="https://www.admissionx.com/{{ $post->make_sub_modelsSlug }}-for-sale{!! ($count > 1)? '?page='.$count.'/' : '/' !!}" title="{{$post->make_sub_modelsName}} Equipment for Sale">{{$post->make_sub_modelsName}} for Sale {!! ($count > 1)? 'Page '.$count : '' !!}</a></li>
		                @endif
		            @endfor
		        @else
		            <li class="lpage"><a href="https://www.admissionx.com/{{ $post->make_sub_modelsSlug }}-for-sale/" title="{{$post->make_sub_modelsName}} for Sale or Rent">{{$post->make_sub_modelsName}} for Sale</a></li>
		        @endif
		    @endforeach

		    <li class="lhead">Country/  <span class="lcount">{{ sizeof($countryForSale) }} pages for sale</span></li>
            @foreach ($countryForSale as $post)
		        {{--*/
		            $countryCount = ceil($post->countryCount/21);
		        /*--}}
		        @if($countryCount > 0)
		            @for( $count = 0; $count <= $countryCount; $count++)
		                @if( $count == 0)
		                    <li class="lpage"><a href="https://www.admissionx.com/{{ $post->countrySlug }}-for-sale{!! ($count > 1)? '?page='.$count.'/' : '/' !!}" title="{{$post->countryName}} Equipment for Sale">{{$post->countryName}} for Sale {!! ($count > 1)? 'Page '.$count : '' !!}</a></li>
		                @endif
		            @endfor
		        @else
		            <li class="lpage"><a href="https://www.admissionx.com/{{ $post->countrySlug }}-for-sale/" title="{{$post->countryName}} for Sale or Rent">{{$post->countryName}} for Sale</a></li>
		        @endif
		    @endforeach

			
			<li class="lhead">Blog/  <span class="lcount">{{ sizeof($getBlogsObj) }} pages</span></li>
			@foreach ($getBlogsObj as $blog)
		        <li class="lpage"><a href="https://www.admissionx.com/blog/{{strtolower($blog->slug)}}" title="{{ $blog->topic }}/">{{ $blog->topic }}</a></li>
		    @endforeach	

		    <li class="lhead">Blog/Category Page</li>
		    @foreach ($getCategoryBlogsObj as $categoryBlog)
		        {{--*/
		            $newstypeCount = ceil($categoryBlog->newstypeCount/10);
		        /*--}}
		        @if($newstypeCount > 0)
		            @for( $count = 0; $count <= $newstypeCount; $count++)
		                @if( $count == 0)
		                	<li class="lpage"><a href="https://www.admissionx.com/news/categories/{{ $categoryBlog->newsslug }}{!! ($count > 1)? '?page='.$count.'' : '' !!}/" title="{{$categoryBlog->news_typesname}} News Category List">{{$categoryBlog->news_typesname}} List {!! ($count > 1)? 'Page '.$count : '' !!}</a></li>
		                @endif
		            @endfor
		        @else
		        	<li class="lpage"><a href="https://www.admissionx.com/news/categories/{{ $categoryBlog->newsslug }}/" title="{{$categoryBlog->news_typesname}} News Category List">{{$categoryBlog->news_typesname}} List</a></li>
		        @endif
		    @endforeach

		    <li class="lhead">Blog/Tag List Page</li>
		    @foreach ($getAllTagBlogsObj as $tagBlog)
		        {{--*/
		            $allTagBlogCount = ceil($tagBlog->allTagBlogCount/10);
		        /*--}}
		        @if($allTagBlogCount > 0)
		            @for( $count = 0; $count <= $allTagBlogCount; $count++)
		                @if( $count == 0)
		                	<li class="lpage"><a href="https://www.admissionx.com/news/tags/{{ $tagBlog->slug }}{!! ($count > 1)? '?page='.$count.'' : '' !!}/" title="{{$tagBlog->name}} News Tags List">{{$tagBlog->name}} Tags News List {!! ($count > 1)? 'Page '.$count : '' !!}</a></li>
		                @endif
		            @endfor
		        @else
		            <li class="lpage"><a href="https://www.admissionx.com/news/tags/{{ $tagBlog->slug }}/" title="{{$tagBlog->name}} News Tags List">{{$tagBlog->name}} Tags News List</a></li>
		        @endif
		    @endforeach
		    <li class="lhead">Trader Listing Page</li>
		    @foreach ($getTraderProductObj as $traderProduct)
		        {{--*/
		            $allTraderProductCount = ceil($traderProduct->allTraderProductCount/20);
		        /*--}}
		        @if($allTraderProductCount > 0)
		            @for( $count = 0; $count <= $allTraderProductCount; $count++)
		                @if( $count == 0)
		                	<li class="lpage"><a href="https://www.admissionx.com/seller-profile/{{ $traderProduct->companySlug }}{!! ($count > 1)? '?page='.$count.'' : '' !!}/" title="{{ $traderProduct->fullname}} Product List">{{ $traderProduct->fullname}} Product List {!! ($count > 1)? 'Page '.$count : '' !!}</a></li>
		                @endif
		            @endfor
		        @else
		            <li class="lpage"><a href="https://www.admissionx.com/seller-profile/{{ $traderProduct->companySlug }}/" title="{{ $traderProduct->fullname}} Product List">{{ $traderProduct->fullname}} Product List</a></li>
		        @endif
		    @endforeach

		    <li class="lhead">Dealer Listing Page</li>
		    @foreach ($getDealerProductObj as $dealerProduct)
		        {{--*/
		            $allDealerProductCount = ceil($dealerProduct->allDealerProductCount/20);
		        /*--}}
		        @if($allDealerProductCount > 0)
		            @for( $count = 0; $count <= $allDealerProductCount; $count++)
		                @if( $count == 0)
		                	<li class="lpage"><a href="https://www.admissionx.com/dealer-profile/{{ $dealerProduct->companySlug }}{!! ($count > 1)? '?page='.$count.'' : '' !!}/" title="{{ $dealerProduct->fullname}} Product List">{{ $dealerProduct->fullname}} Product List {!! ($count > 1)? 'Page '.$count : '' !!}</a></li>
		                @endif
		            @endfor
		        @else
		            <li class="lpage"><a href="https://www.admissionx.com/dealer-profile/{{ $dealerProduct->companySlug }}/" title="{{ $dealerProduct->fullname}} Product List">{{ $dealerProduct->fullname}} Product List</a></li>
		        @endif
		    @endforeach


		    <li class="lhead">Package Product List Page</li>
		    @foreach ($searchProductObj as $packageProduct)
		        {{--*/
		            $productCount = ceil($packageProduct->productCount/18);
		        /*--}}
		        @if($productCount > 0)
		            @for( $count = 0; $count <= $productCount; $count++)
		                @if( $count == 0)
		                	<li class="lpage"><a href="https://www.admissionx.com/search?packages={{ $packageProduct->package_id }}{!! ($count > 1)? '&amp;page='.$count.'' : '' !!}/" title="Machinery Planet {{$packageProduct->packagesName}} Page">Machinery Planet {{$packageProduct->packagesName}} Page {!! ($count > 1)? $count : '' !!}</a></li>
		                @endif
		            @endfor
		        @else
		        	<li class="lpage"><a href="https://www.admissionx.com/search?packages={{$packageProduct->package_id}}/" title="Machinery Planet {{$packageProduct->packagesName}} Page">Machinery Planet {{$packageProduct->packagesName}} Page </a></li>
		        @endif
		    @endforeach

		    <li class="lhead">Buy/Rent Product List Page</li>
		    @foreach ($buyRentProductObj as $buyrent)
		        {{--*/
		            $productCount = ceil($buyrent->productCount/18);
		        /*--}}
		        @if($productCount > 0)
		            @for( $count = 0; $count <= $productCount; $count++)
		                @if($buyrent->productType == 1)
		                    @if( $count == 0)
		                    	<li class="lpage"><a href="https://www.admissionx.com/buy-machinery{!! ($count > 1)? '?page='.$count.'' : '' !!}/" title="Buy Product List Page">Buy Product List Page {!! ($count > 1)? $count : '' !!}</a></li>
		                    @endif
		                @elseif($buyrent->productType == 2)
		                    @if( $count == 0)
		                    	<li class="lpage"><a href="https://www.admissionx.com/rent-machinery{!! ($count > 1)? '?page='.$count.'' : '' !!}/" title="Rent Product List Page">Rent Product List Page {!! ($count > 1)? $count : '' !!}</a></li>
		                    @endif
		                @elseif($buyrent->productType == 4)
		                    @if( $count == 0)
		                    	<li class="lpage"><a href="https://www.admissionx.com/auction-machinery{!! ($count > 1)? '?page='.$count.'' : '' !!}/" title="Auction Product List Page">Auction Product List Page {!! ($count > 1)? $count : '' !!}</a></li>
		                    @endif
		                @else
		                    @if( $count > 0)
		                    	<li class="lpage"><a href="https://www.admissionx.com/search/?productType={{$buyrent->productType}}{!! ($count > 1)? '&page='.$count.'' : '' !!}/" title="{{ $buyrent->productTypeName }} Product List Page">{{ $buyrent->productTypeName }} Product List Page {!! ($count > 1)? $count : '' !!}</a></li>
		                    @endif
		                @endif
		            @endfor
		        @endif
		    @endforeach

		    {{--*/ 
		        $allProduct = sizeof($productObj);
		        $searchCount = ceil($allProduct/18);

		        $allTrader = sizeof($getTraderProductObj);
		        $traderCount = ceil($allTrader/10);

		        $allDealer = sizeof($getDealerProductObj);
		        $dealerCount = ceil($allDealer/10);
		    /*--}}
		    <li class="lhead">Machinery planet Search Page</li>    
		    @if($searchCount > 0)
		        @for( $counts = 0; $counts <= $searchCount; $counts++)
		            @if( $counts > 0)
		            	<li class="lpage"><a href="https://www.admissionx.com/search{!! ($counts > 1)? '?page='.$counts.'' : '' !!}/" title="Machinery planet search page">Machinery planet Search Page {!! ($counts > 1)? $counts : '' !!}</a></li>
		            @endif
		        @endfor
		    @endif
		    <li class="lhead">Find Seller List Page</li>
		    @if($traderCount > 0)
		        @for( $countTrader = 0; $countTrader <= $traderCount; $countTrader++)
		            @if( $countTrader > 0)
		            	<li class="lpage"><a href="https://www.admissionx.com/seller-listing{!! ($countTrader > 1)? '?page='.$countTrader.'' : '' !!}/" title="Find Seller Page | admissionx.com">Find Seller Page {!! ($countTrader > 1)? $countTrader : '' !!}</a></li>
		            @endif
		        @endfor
		    @endif

		    <li class="lhead">Find Dealer List Page</li>
		    @if($dealerCount > 0)
		        @for( $countDealer = 0; $countDealer <= $dealerCount; $countDealer++)
		            @if( $countDealer > 0)
		            	<li class="lpage"><a href="https://www.admissionx.com/dealer-listing{!! ($countDealer > 1)? '?page='.$countDealer.'' : '' !!}/" title="Find Dealer Page | admissionx.com">Find Dealer Page {!! ($countDealer > 1)? $countDealer : '' !!}</a></li>
		            @endif
		        @endfor
		    @endif

		    
		    <li class="lhead">City/  <span class="lcount">{{ sizeof($cityForSale) }} pages for sale</span></li>
            @foreach ($cityForSale as $post)
		        {{--*/
		            $cityCount = ceil($post->cityCount/21);
		        /*--}}
		        @if($cityCount > 0)
		            @for( $count = 0; $count <= $cityCount; $count++)
		                @if( $count == 0)
		                    <li class="lpage"><a href="https://www.admissionx.com/{{ $post->citySlug }}-for-sale{!! ($count > 1)? '?page='.$count.'/' : '/' !!}" title="{{$post->cityName}} Equipment for Sale">{{$post->cityName}} for Sale {!! ($count > 1)? 'Page '.$count : '' !!}</a></li>
		                @endif
		            @endfor
		        @else
		            <li class="lpage"><a href="https://www.admissionx.com/{{ $post->citySlug }}-for-sale/" title="{{$post->cityName}} for Sale or Rent">{{$post->cityName}} for Sale</a></li>
		        @endif
		    @endforeach

		    <li class="lhead">City/  <span class="lcount">{{ sizeof($cityForRent) }} pages for rent</span></li>
            @foreach ($cityForRent as $post)
		        {{--*/
		            $cityCount = ceil($post->cityCount/21);
		        /*--}}
		        @if($cityCount > 0)
		            @for( $count = 0; $count <= $cityCount; $count++)
		                @if( $count == 0)
		                    <li class="lpage"><a href="https://www.admissionx.com/{{ $post->citySlug }}-for-rent{!! ($count > 1)? '?page='.$count.'/' : '/' !!}" title="{{$post->cityName}} Equipment for Rent">{{$post->cityName}} for Rent {!! ($count > 1)? 'Page '.$count : '' !!}</a></li>
		                @endif
		            @endfor
		        @else
		            <li class="lpage"><a href="https://www.admissionx.com/{{ $post->citySlug }}-for-rent/" title="{{$post->cityName}} for Rent">{{$post->cityName}} for Rent</a></li>
		        @endif
		    @endforeach

		    <li class="lhead">City/  <span class="lcount">{{ sizeof($cityForAuction) }} pages for auction</span></li>
            @foreach ($cityForAuction as $post)
		        {{--*/
		            $cityCount = ceil($post->cityCount/21);
		        /*--}}
		        @if($cityCount > 0)
		            @for( $count = 0; $count <= $cityCount; $count++)
		                @if( $count == 0)
		                    <li class="lpage"><a href="https://www.admissionx.com/{{ $post->citySlug }}-for-auction{!! ($count > 1)? '?page='.$count.'/' : '/' !!}" title="{{$post->cityName}} Equipment for auction">{{$post->cityName}} for auction {!! ($count > 1)? 'Page '.$count : '' !!}</a></li>
		                @endif
		            @endfor
		        @else
		            <li class="lpage"><a href="https://www.admissionx.com/{{ $post->citySlug }}-for-auction/" title="{{$post->cityName}} for auction">{{$post->cityName}} for auction</a></li>
		        @endif
		    @endforeach

		</ul>
	</div>
	<div id="footer">
		<a target="_blank" href="https://www.admissionx.com">Machinery Planet html sitemaps</a> | Copyright &copy; 2016 - <?php echo date('Y'); ?>
	</div>
</body>

</html>
			
@endsection


