@extends('website/new-design-layouts.master')
@section('content')

<!-- <div class="container  content-sm">
	<div class="container">
		<div class="row">
			<div class="col-md-12 md-margin-bottom-50">
			</div>
		</div>
	</div>
</div> -->

 <nav class="navbar navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
			<li><a href="{{ URL::to('terms-of-service') }}">Terms Of Service</a></li>
			<li><a href="{{ URL::to('privacy-policy') }}">Privacy Policy</a></li>
			<li><a href="{{ URL::to('payments-refunds-policy') }}">Payments & Refunds Policy</a></li>
			<li><a href="{{ URL::to('cancellation-refunds') }}">Cancellation & Refunds</a></li>
			<!-- <li><a href="{{ URL::to('student-referral-policy') }}">Student referral policy</a></li> -->
			<li><a href="{{ URL::to('admission-registration-policy') }}">Admission Registration Policy</a></li>
			<li><a href="{{ URL::to('advertiser-agreement') }}">Advertiser Agreement</a></li>
			@if(Auth::check())									
				{{--*/   $getLoggedObj = DB::table('users')
						->where('users.id', '=', Auth::id())
	                    ->where('users.userrole_id','=','2')
	                    ->select('users.id')
	                    ->take(1)
	                    ->get()
	                    ;
	        	/*--}}
	        	@if( $getLoggedObj )
	        	<li><a href="{{ URL::to('college-partner-agreement') }}" class="active" style="color: #fff;">College Agreement</a></li>	
				@endif
			@endif
		</ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

<div class="container">
	<div class="col-md-12">
		<div class="container content">
			<div class="row-fluid privacy">
				@foreach($getPageContentDataObj as $item)
					<div class="overflow-h">
						<h3>{{ $item->title }}</h3>
						{!! $item->description !!}
					</div>
				@endforeach
				<!-- <h4><strong>Clauses for the agreement between AdmissionX and colleges:</strong></h4>
				<br />
				<ol>
					<li> At the time of taking admission, the student pays Rs. 499 as a part of the college fees online to AdmissionX website. College agrees to deduct this amount (Rs. 499) from the 1st year fee chargeable to the student.</li>
					<li>The annual fee amount for any particular student, for the entire duration of the course, must not exceed the amount mentioned in the provisional admission letter issued by AdmissionX to that particular student.</li>
					<li>College cannot deny admission to any particular student (within the deadline period, decided by AdmissionX), once the provisional admission letter has been generated by AdmissionX to that particular student.</li>
				</ol> -->
			</div><!--/row-fluid-->
		</div><!--/container-->
	</div>
</div>
			
@endsection


